# -*- coding: utf-8 -*-
"""Translate Yonghe Martial Codex character-sheet .xlsx files (CN->EN).
Translation only: writes to EN target dir, never modifies CN source.
Uses locked glossary terms; character names -> pinyin per 角色圖 convention.
"""
import openpyxl, re, os

CN = r"J:/Buddycode/2026-06-21-13-01-27/rules_source/中文/永和武典/sheets"
EN = r"J:/Buddycode/2026-06-21-13-01-27/rules_source/英文/永和武典/sheets"

FILES = ["Boss角色卡合集.xlsx","NPC同伴卡合集.xlsx","NPC角色卡合集.xlsx","一流劍客.xlsx",
"全角色卡合集.xlsx","公輸玄.xlsx","六扇門堂主.xlsx","六扇門捕快.xlsx","包小乙.xlsx","南宮晦.xlsx",
"厲殘陽.xlsx","唐門外圍弟子.xlsx","塞外刀客.xlsx","墨染.xlsx","夜修羅.xlsx","天劍盟長老.xlsx",
"孟婆.xlsx","少林武僧.xlsx","山賊嘍囉.xlsx","山賊頭目.xlsx"]

CJK = re.compile(r'[一-鿿]')
FILE_REF = re.compile(r'\.(png|xlsx|svg)$|[\\]')

EXACT = {
# ---- headers / section titles ----
"永 和 武 典": "Yonghe Martial Codex",
"角色卡 · 跑團規則工作室": "Character Card · Tabletop Rules Studio",
"朝廷NPC · 跑團規則工作室": "Court NPC · Tabletop Rules Studio",
"NPC同伴卡 · 單人專用": "NPC Companion Card · Solo Only",
"— 基本資料 —": "-- Basic Info --",
"— 六維屬性 —": "-- Six Attributes --",
"— 技能 —": "-- Skills --",
"— 技能（簡化） —": "-- Skills (Simplified) --",
"— 招式與能力 —": "-- Moves & Abilities --",
"— 持有物品 —": "-- Possessions --",
"— 武功 —": "-- Martial Arts --",
"— 衍生值 —": "-- Derived Values --",
"— 裝備 —": "-- Equipment --",
# ---- basic-info labels ----
"角色名": "Character Name",
"玩家": "Player",
"門派": "Sect",
"境界": "Realm",
"概念": "Concept",
"內功": "Internal Art",
"內功·心法": "Internal Art · Mental Method",
"內功·硬功": "Internal Art · Hard Art",
"內功係數": "Internal Art Coefficient",
"內功係數2": "Internal Art Coefficient 2",
"內功係數2，真氣池10": "Internal Art Coefficient 2, Qi Pool 10",
"內功係數2，真氣池16": "Internal Art Coefficient 2, Qi Pool 16",
"內功係數2，真氣池8": "Internal Art Coefficient 2, Qi Pool 8",
"內功係數3": "Internal Art Coefficient 3",
"內功係數4": "Internal Art Coefficient 4",
"內功係數5": "Internal Art Coefficient 5",
"內功係數5 全屬性+1": "Internal Art Coefficient 5, all attributes +1",
"內功: 0(無內功)": "Internal Art: 0 (No Internal Art)",
"內功: 1(無內功)": "Internal Art: 1 (No Internal Art)",
"內功: 3(正宗)": "Internal Art: 3 (Orthodox)",
"內功: 5(絕世)": "Internal Art: 5 (Peerless)",
"0(無內功)": "0 (No Internal Art)",
"1(無內功)": "1 (No Internal Art)",
"外功": "External Art",
"外功·刀法": "External Art · Saber",
"外功·劍術": "External Art · Swordsmanship",
"外功·拳掌": "External Art · Fist & Palm",
"外功·斧": "External Art · Axe",
"外功·暗器": "External Art · Hidden Weapon",
"外功·棍法": "External Art · Staff",
"外功·毒術": "External Art · Poisoncraft",
"外功·短兵": "External Art · Short Weapon",
"外功·鈍器": "External Art · Blunt",
# ---- realm names ----
"初窺門徑": "First Glimpse",
"入門·初窺門徑": "Initiate · First Glimpse",
"入門": "Initiate",
"登堂入室": "Crossing the Threshold",
"第二境·登堂入室": "Second Realm · Crossing the Threshold",
"融會貫通": "Complete Mastery",
"第三境·融會貫通": "Third Realm · Complete Mastery",
"爐火純青": "Perfecting the Craft",
"第四境·爐火純青": "Fourth Realm · Perfecting the Craft",
"登峯造極": "Peak of Perfection",
"返璞歸真": "Return to Simplicity",
"上乘": "Superior",
"上乘·遠攻": "Superior · Long-range",
"上乘輕功": "Superior Lightfoot",
"正宗": "Orthodox",
"絕世": "Peerless",
"絕世內功": "Peerless Internal Art",
"精進": "Proficiency",
"進階": "Advanced",
"進階·小有所成": "Advanced · Minor Accomplishment",
"進階輕功": "Advanced Lightfoot",
"層級": "Tier",
"層級·精進": "Tier · Proficiency",
"特殊": "Special",
"特殊·機關": "Special · Trapcraft",
"特殊·毒術": "Special · Poisoncraft",
"特殊·硬功": "Special · Hard Art",
"特殊·醫術": "Special · Medicine",
# ---- attributes ----
"膂力 STR": "Strength STR",
"身法 DEX": "Agility DEX",
"根骨 CON": "Constitution CON",
"悟性 INT": "Comprehension INT",
"定力 WIS": "Willpower WIS",
"魅力 CHA": "Charisma CHA",
"膂力（STR）": "Strength (STR)",
"身法（DEX）": "Agility (DEX)",
"根骨（CON）": "Constitution (CON)",
"悟性（INT）": "Comprehension (INT)",
"定力（WIS）": "Willpower (WIS)",
"魅力（CHA）": "Charisma (CHA)",
# ---- attribute sub-labels ----
"屬性": "Attribute",
"屬性合計": "Attribute Total",
"屬性飆升每回合自損": "Attribute surge self-damages each round",
"基礎值": "Base Value",
"調整值": "Modifier",
"對應屬性": "Corresponding Attribute",
"加值": "Bonus",
"等級": "Level",
# ---- skills ----
"輕功": "Lightfoot",
"識武": "Technique Reading",
"追蹤": "Tracking",
"潛行": "Stealth",
"野外求生": "Survival",
"口才": "Oratory",
"威嚇": "Intimidate",
"察言觀色": "Read Intent",
"江湖見識": "Jianghu Lore",
"醫術": "Medicine",
"易容": "Disguise",
"丹術": "Alchemy",
"機關術": "Trapcraft",
"書畫": "Calligraphy & Painting",
"攀爬": "Climbing",
"開鎖": "Lockpicking",
"盜竊": "Pickpocket",
"輕功等級": "Lightfoot Level",
# ---- derived values ----
"衍生值": "Derived Values",
"生命值（HP）": "HP",
"真氣": "Qi",
"先手": "Initiative",
"閃避": "Evasion",
"防禦": "Defense",
"防禦DC": "Defense DC",
"防禦（DC）": "Defense (DC)",
"身法+定力": "Agility + Willpower",
"身法調整+輕功等級": "Agility Modifier + Lightfoot Level",
"身法調整值": "Agility Modifier",
"根骨調整+護甲值": "Constitution Modifier + Armor Value",
"根骨調整值": "Constitution Modifier",
"根骨×5+境界": "Constitution ×5 + Realm",
"根骨x內功係數+境界": "Constitution × Internal Art Coefficient + Realm",
"根骨×5+境界加值": "Constitution ×5 + Realm Bonus",
"根骨×內功係數+境界加值": "Constitution × Internal Art Coefficient + Realm Bonus",
"外傷減免": "External Injury Reduction",
"俠義": "Heroism",
"俠義值": "Heroism",
"惡名": "Infamy",
"惡名值": "Infamy",
"戰術": "Tactics",
"勢力": "Faction",
# ---- martial-arts table columns ----
"類型": "Type",
"勁力": "Force",
"傷害/效果": "Damage/Effect",
"傷害": "Damage",
"效果": "Effect",
"命中": "Hit",
"命中修正": "Hit Modifier",
"使用次數": "Uses",
"名稱": "Name",
"武功名": "Martial Art Name",
"描述": "Description",
"範圍": "Range",
"反應": "Reaction",
"被動": "Passive",
"被動·劍意": "Passive · Sword Intent",
"被動·醫者之心": "Passive · Healer's Heart",
"心眼": "Mind's Eye",
"標記目標": "Mark Target",
"機動+2": "Mobility +2",
"招式": "Move",
"武器": "Weapon",
"護甲": "Armor",
"護甲值": "Armor Value",
"道具": "Item",
"備註": "Notes",
# ---- skill/derived section labels ----
"技能": "Skills",
"技能（簡化）": "Skills (Simplified)",
"武功": "Martial Arts",
"裝備": "Equipment",
"六維屬性": "Six Attributes",
"基本資料": "Basic Info",
"持有物品": "Possessions",
"招式與能力": "Moves & Abilities",
# ---- taxonomy labels ----
"刀法": "Saber Art",
"劍法": "Sword Art",
"劍意": "Sword Intent",
"劍陣": "Sword Formation",
"拳掌": "Fist & Palm",
"棍法": "Staff Art",
"槍法": "Spear Art",
"暗器": "Hidden Weapon",
"暗殺": "Assassination",
"暗殺標記": "Assassination Mark",
"暗殺術": "Assassination Art",
"毒術": "Poisoncraft",
"易容術": "Disguise Art",
"醫術": "Medicine",
# ---- force / damage / status tokens (used in moves & prose) ----
"快": "Swift",
"剛": "Firm",
"柔": "Gentle",
"巧": "Subtle",
"重": "Heavy",
"遠": "Long-range",
"遠攻": "Long-range Attack",
"遠程掩護（被動）": "Ranged Cover (Passive)",
"外傷": "External Injury",
"內傷": "Internal Injury",
"中毒": "Poison",
"封脈": "Sealed Meridian",
"混合": "Mixed",
"狂暴": "Berserk",
"狂熱衝鋒": "Fanatic Charge",
"威嚇": "Intimidate",
"震懾威嚇": "Intimidate and Overawe",
"官威震懾": "Official Might Intimidation",
"喝令": "Command",
"抄傢夥": "Draw Weapon",
"酌情辦理": "Handle as Appropriate",
# ---- generic enemy / NPC card type labels ----
"劇本敵人卡": "Scripted Enemy Card",
"通用敵人卡": "Generic Enemy Card",
"一流劍客": "First-Rate Swordsman",
"江湖散修": "Jianghu Independent Cultivator",
"江湖老怪": "Jianghu Old Eccentric",
"獨行刺客": "Lone Assassin",
"街頭潑皮": "Street Hooligan",
"山賊嘍囉": "Mountain Bandit Mook",
"山賊頭目": "Mountain Bandit Chief",
"六扇門捕快": "Six Doors Constable",
"六扇門堂主": "Six Doors Bureau Chief",
"唐門外圍弟子": "Tang Sect Outer Disciple",
"少林武僧": "Shaolin Monk",
"塞外刀客": "Frontier Saber Master",
"天劍盟長老": "Tianjian Alliance Elder",
"隱世宗師": "Hidden Grandmaster",
"鏢局趟子手": "Escort Agency Porter",
"魔教外圍教徒": "Demon Cult Outer Disciple",
"魔教護法": "Demon Cult Guardian",
"血月教精英教徒": "Blood Moon Cult Elite Disciple",
"血月教長老": "Blood Moon Cult Elder",
"蠻族勇士": "Barbarian Warrior",
"江湖散人": "Jianghu Independent",
# ---- character names (pinyin, 角色圖 convention) ----
"柳如風": "Liu Rufeng",
"柳生煙": "Liu Shengyan",
"柳生煙(同伴)": "Liu Shengyan (Companion)",
"段天涯": "Duan Tianya",
"段天涯(同伴)": "Duan Tianya (Companion)",
"蘇青囊": "Su Qingnang",
"墨染": "Mo Ran",
"厲殘陽": "Li Canyang",
"夜修羅": "Ye Xiuluo",
"紫陽": "Ziyang",
"沈萬金": "Shen Wanjin",
"慧覺": "Huijue",
"公輸玄": "Gongshu Xuan",
"孟婆": "Meng Po",
"清虛": "Qingxu",
"楚懷沙": "Chu Huaisha",
"燕飛雲": "Yan Feiyun",
"金日磾": "Jin Ridi",
"鐵山": "Tieshan",
"鐵鏡心": "Tie Jingxin",
"韓豹": "Han Bao",
"韓鐵衣": "Han Tieyi",
"韓鐵衣(同伴)": "Han Tieyi (Companion)",
"趙無極": "Zhao Wuji",
"曹少欽": "Cao Shaoqin",
"白鶴": "Baihe",
"蘇小妹": "Su Xiaomei",
"朱雀": "Zhuque",
"南宮晦": "Nangong Hui",
"包小乙": "Bao Xiaoyi",
"殘陽": "Setting Sun",
# ---- sect / faction names ----
"六扇門": "Six Doors",
"六扇門官服": "Six Doors Official Robe",
"六扇門洛陽分堂堂主，朝廷在江湖的終極武裝。鐵面無私，武功剛正不留餘地。天榜#8。":
"Branch Master of the Six Doors Luoyang branch, the court's ultimate armed force in the jianghu. Iron-faced and impartial, his martial art is upright with no quarter given. Heaven Ranking #8.",
"六扇門中層官員，武功紮實經驗豐富。": "Mid-level official of the Six Doors, solid martial skill and rich experience.",
"六扇門見習捕快。入行三年未得真傳——代表朝廷最基層的武力。":
"Six Doors apprentice constable. Three years in without true transmission — represents the court's most grassroots martial force.",
"天劍盟": "Tianjian Alliance",
"天劍盟烈陽劍主·簡化版。年輕有為卻陷入「正道的代價」困境。在禪位之爭中選擇獨行。":
"Lieyang Sword Master of the Tianjian Alliance · simplified version. Promising yet trapped in the dilemma of 'the cost of righteousness.' Chose to go alone in the succession struggle.",
"天劍盟烈陽劍主，年約三十五，劍法剛猛霸道，少壯鷹派領袖。":
"Lieyang Sword Master of the Tianjian Alliance, about 35, fierce and overbearing sword art, young hawkish leader.",
"天劍盟盟主，年過六旬的劍道泰斗。三十年前以一人一劍平定西域十三寇。":
"Alliance Leader of the Tianjian Alliance, a sword grandmaster over sixty. Thirty years ago pacified the thirteen bandits of the Western Regions with one man and one sword.",
"天劍盟老一輩劍術宗師，劍法已入化境。": "Older-generation sword grandmaster of the Tianjian Alliance, his sword art has reached a transcendent state.",
"千機閣": "Qianji Pavilion",
"千機閣閣主，算術天才，正面戰力二流但機關戰術超一流。":
"Pavilion Lord of Qianji Pavilion, an arithmetic prodigy; mediocre in direct combat but a supreme master of mechanical tactics.",
"丐幫年輕弟子，從小在街上混大的，什麼人都認識、什麼地方都去過。隊伍裡的萬金油。":
"Young disciple of the Beggar Sect, grew up on the streets, knows everyone and has been everywhere. The team's jack-of-all-trades.",
"唐門基層弟子，擅長暗器與毒術入門。": "Grassroots disciple of the Tang Sect, skilled in hidden weapons and beginner poisoncraft.",
"唐門年輕女弟子，從小在暗器堆裡長大，手指靈巧得能同時夾住三枚飛針。性格古靈精怪，戰鬥中絕不近身。":
"Young female disciple of the Tang Sect, grew up among hidden weapons, deft enough to hold three flying needles at once. Quirky personality, never engages in close combat.",
"四海盟": "Sihai Alliance",
"四海盟大掌櫃，江湖首富，武功稀鬆但錢能通神。": "Chief manager of the Sihai Alliance, the richest in the jianghu; weak martial skill but money works miracles.",
"太虛宮": "Taixu Palace",
"太虛宮劍閣首座，只會用劍說話的清冷道者，劍在鞘裡最可怕。":
"Chief of the Sword Pavilion of Taixu Palace, a cold Taoist who only speaks with his sword; most fearsome with the sword in its sheath.",
"少林俗家弟子，自幼在山門習武，一身橫肉硬得像鐵。性格耿直豪爽，不善言辭但極重義氣。隊伍裡永遠站在最前面。":
"Lay disciple of Shaolin, trained at the mountain gate since childhood, built like iron. Upright and cheerful, poor with words but values loyalty highly. Always stands at the front of the group.",
"少林寺護院僧人，守護山門的武僧。": "Temple-guarding monk of Shaolin Monastery, a martial monk defending the mountain gate.",
"山寨的頭領，比普通嘍囉強悍，有小頭目級實力。": "Leader of the bandit stronghold, tougher than ordinary mooks, with petty-chief-level strength.",
"市井混混，三五成羣收保護費。拳頭不硬膽子不小，見血就腿軟。":
"Street punk, extorts protection money in small groups. Soft fists but big nerves, legs go weak at the sight of blood.",
"文官型NPC。不會武功。以話術/權謀/制度作戰。HP 15": "Civil-official-type NPC. No martial skill. Fights with rhetoric / scheming / institutions. HP 15",
"文官型NPC。不會武功。以話術/權謀/制度作戰。生命值（HP） 15": "Civil-official-type NPC. No martial skill. Fights with rhetoric / scheming / institutions. HP 15",
"江湖散人，為救妹妹不惜一切的「普通人」。無門無派，靠機關術和輕功行走江湖。":
"Jianghu independent, an 'ordinary person' who stops at nothing to save his sister. No sect, walks the jianghu relying on trapcraft and lightfoot.",
"歸隱多年的老江湖，武功深不可測但已年老體衰。": "A veteran of the jianghu in seclusion for years, unfathomable martial skill but aged and frail.",
"無門無派的獨行武者，自學成才但基礎紮實。": "A sectless lone warrior, self-taught but with solid foundations.",
"武當年輕道士，參悟道家心法已有小成。性格沉穩內斂，不爭不搶卻極有主見。戰鬥中長於以柔克剛、消耗對手。":
"Young Taoist of Wudang, has attained minor success in Taoist mental methods. Calm and reserved, never competes yet very opinionated. Excels at using softness against hardness and wearing down opponents.",
"滲透型NPC。HP 40, 真氣 22。惡名記在西廠名下。": "Infiltration-type NPC. HP 40, Qi 22. Infamy recorded under the Western Factory.",
"滲透型NPC。生命值（HP） 40, 真氣 22。惡名記在西廠名下。": "Infiltration-type NPC. HP 40, Qi 22. Infamy recorded under the Western Factory.",
"職業殺手，一擊斃命後立刻脫離。": "Professional killer, strikes lethally then withdraws immediately.",
"華山青年劍客，家傳劍法天賦出眾，性格仗義直爽但略帶衝動。戰鬥中追求以快打慢、先發制人。":
"Young swordsman of Huashan, outstanding talent in family sword art, righteous and direct but slightly impulsive. Pursues speed-over-slow and striking first.",
"藥王谷濟世堂年輕女醫。不收錢治病，心軟但手穩。為尋找失蹤的師父行走江湖。":
"Young female doctor of Yaowang Valley's Healing Hall. Treats without charge, soft-hearted but steady-handed. Walks the jianghu searching for her missing master.",
"藥王谷濟世堂首席，十九歲女醫，背藥箱行走江湖，不收錢治病。":
"Chief of Yaowang Valley's Healing Hall, a 19-year-old female doctor, walks the jianghu with a medicine box, treats without charge.",
"藥王谷谷主，年過五十貌若三十，天下第一神醫，不問立場只問病情。":
"Valley Lord of Yaowang Valley, over fifty yet looking thirty, the world's foremost divine physician, asks only about the illness not the allegiance.",
"血月教中層，經過血月儀式強化的狂信徒。": "Mid-level Blood Moon Cult member, a fanatic strengthened by the Blood Moon ritual.",
"血月教最底層信徒，狂熱但武功稀鬆。": "Lowest-tier Blood Moon Cult believer, fanatical but weak in martial skill.",
"血月教核心高層，掌握禁忌魔功。": "Core high-ranking Blood Moon Cult member, wields forbidden demonic arts.",
"血月教高層護法，魔功深厚。": "High-ranking Blood Moon Cult Guardian, deep demonic arts.",
"血月教大護法，以戰鬥為信仰的狂人，渾身傷疤，越戰越狂。":
"Grand Guardian of the Blood Moon Cult, a battle-as-faith fanatic, scarred all over, grows wilder the more he fights.",
"血月教教主，來歷成謎，戴修羅面具，最有腦子的魔頭。":
"Cult Leader of the Blood Moon Cult, origin a mystery, wears the Asura mask, the most cunning demon lord.",
"西廠四大暗探之首，專長臥底滲透。真實面目無人知曉。":
"Head of the Western Factory's four great spies, specializes in undercover infiltration. True face known to none.",
"西廠掌印太監。修習吸星大法殘篇與玄陰指，朝廷暗面的掌控者。":
"Chief Eunuch of the Western Factory. Practices the residual fragments of the Star-Absorbing Great Method and the Mysterious Yin Finger, controller of the court's dark side.",
"走鏢的護衛，經驗豐富但非武林高手。": "Escort guard, experienced but not a martial arts master.",
"朝廷公差，受過正規訓練，三人一組巡邏。": "Court official errand-runner, formally trained, patrols in groups of three.",
"朝廷欽差，武舉主考官。不會武功但話術和權謀可鎮壓多數江湖人。":
"Court Imperial Commissioner, examiner for the martial exam. No martial skill but rhetoric and scheming can suppress most jianghu folk.",
"禁軍副統領·簡化版。身材魁梧如鐵塔的正直軍人。在官場被壓了十年——寧折不彎。":
"Deputy Commander of the Imperial Guard · simplified version. An upright soldier built like an iron tower. Suppressed in the bureaucracy for ten years — would rather break than bend.",
"禁軍副統領，禁軍槍法唯一傳人。曾在皇城保衛戰獨守承天門。":
"Deputy Commander of the Imperial Guard, sole heir of the Imperial Guard Spear Art. Once held Chengtian Gate alone in the capital defense battle.",
"黑風寨大當家「獨眼龍」，盤踞黑風寨劫掠商旅。修習魔教殘篇，走火入魔前兆。":
"Chief of Black Wind Stronghold 'One-Eyed Dragon', entrenched at Black Wind Stronghold plundering merchants. Practices demonic cult fragments, showing early signs of Qi Deviation.",
"西域來的刀客，刀法狂野不羈。": "A saber master from the Western Regions, wild and untamed saber art.",
"逍遙派年輕傳人，身法天賦萬中無一。性格灑脫不羈，對規矩和權威有天然的排斥。":
"Young heir of the Xiaoyao Sect, one-in-ten-thousand talent in agility. Free and uninhibited, naturally rejecting of rules and authority.",
"落草為寇的窮苦人，刀法粗糙人多勢眾。": "Poor folk turned bandits, crude saber art but great in numbers.",
"忘川樓樓主，戴白瓷面具，暗殺術可威脅第五境。":
"Tower Lord of Wangchuan Tower, wears a white-porcelain mask, assassination art can threaten the Fifth Realm.",
"萬佛寺方丈，第五境巔峯，得道高僧，無我境中的困惑者。":
"Abbot of Wanfo Temple, Fifth Realm pinnacle, an enlightened monk, a perplexed one within the state of no-self.",
"藥王谷幽冥堂主，毒術天才，厭世感與毒系的冷酷魅力。":
"Hall Master of Yaowang Valley's Netherworld Hall, a poisoncraft prodigy, with a world-weary feel and the cold charm of the poison path.",
"原藥王谷幽冥堂副堂主，叛逃後投靠血月教。家人被扣為人質。":
"Former Deputy Hall Master of Yaowang Valley's Netherworld Hall, defected to the Blood Moon Cult. Family held hostage.",
"蠻族最高統帥，擁有與萬象洞天武脈同源的「獸王之血」。草原連續大旱被迫南侵。":
"Supreme commander of the Barbarians, possessing the 'Beast King's Blood' shared in origin with the martial vein of Wanxiang Grotto. Consecutive droughts on the grasslands forced a southern invasion.",
"不為人知的絕世高手，若非因緣際會不會出手。": "An unknown peerless master who would not act unless fate brought it about.",
# ---- boss / npc mechanic strings ----
"Boss機制：每回合自動回1d6 HP(火攻可破)；瀕死釋放毒霧。HP 45，真氣 30":
"Boss mechanic: auto-recover 1d6 HP each round (breakable by fire attack); release poison mist when dying. HP 45, Qi 30",
"Boss機制：每回合自動回1d6 生命值（HP）(火攻可破)；瀕死釋放毒霧。生命值（HP） 45，真氣 30":
"Boss mechanic: auto-recover 1d6 HP each round (breakable by fire attack); release poison mist when dying. HP 45, Qi 30",
"Boss機制：狂暴疊加+受傷恐懼瓦解。生命值（HP） 30，真氣 6":
"Boss mechanic: stacking Berserk + collapses from fear of injury. HP 30, Qi 6",
"終局Boss·第六境。弱點：內傷對其1.5倍。可和平路線(魅力難度（DC）22)。生命值（HP） 100":
"Final Boss · Sixth Realm. Weakness: Internal Injury deals 1.5× to it. Peaceful route possible (Charisma DC 22). HP 100",
"終極NPC。防禦DC20。弱點:膂力低HP中等。HP 55, 真氣 55":
"Ultimate NPC. Defense DC 20. Weakness: low Strength, medium HP. HP 55, Qi 55",
"終極NPC。防禦（DC）20。弱點:膂力低生命值（HP）中等。生命值（HP） 55, 真氣 55":
"Ultimate NPC. Defense (DC) 20. Weakness: low Strength, medium HP. HP 55, Qi 55",
"第一境巔峯。HP 20, 真氣 4": "First Realm pinnacle. HP 20, Qi 4",
"第一境巔峯。生命值（HP） 20, 真氣 4": "First Realm pinnacle. HP 20, Qi 4",
"第四境。朝廷終極武力。HP 55, 真氣 34": "Fourth Realm. The court's ultimate martial force. HP 55, Qi 34",
"第四境。朝廷終極武力。生命值（HP） 55, 真氣 34": "Fourth Realm. The court's ultimate martial force. HP 55, Qi 34",
"非Boss戰--不想殺人只想脫身。生命值（HP） 28，真氣 20":
"Non-Boss fight — doesn't want to kill, only to escape. HP 28, Qi 20",
# ---- companion-rule references (keep .md token) ----
"同伴規則見20_單人規則.md §4。不消耗真氣——改為使用次數。":
"Companion rules see 20_單人規則.md §4. Does not consume Qi — instead uses limited uses.",
"同伴規則見20_單人規則.md §4。不消耗真氣——改為招式使用次數限制。":
"Companion rules see 20_單人規則.md §4. Does not consume Qi — instead move uses are limited.",
"同伴規則見20_單人規則.md §4。武功不消耗真氣——改為使用次數。":
"Companion rules see 20_單人規則.md §4. Martial arts do not consume Qi — instead use limited uses.",
# ---- study-with-master entries ----
"可拜師(難度（DC）10): 入門醫術。非武功線。": "Can take as master (DC 10): Initiate Medicine. Not a martial-art path.",
"可拜師(難度（DC）10): 口才/江湖見識。贈50兩。": "Can take as master (DC 10): Oratory / Jianghu Lore. Gifts 50 taels.",
"可拜師(難度（DC）12): 烈陽劍法+烈陽心經。": "Can take as master (DC 12): Lieyang Sword Art + Lieyang Heart Sutra.",
"可拜師(難度（DC）14): 兩儀劍法+先天功。每月指點。": "Can take as master (DC 14): Two-Forms Sword Art + Pre-Heaven Art. Monthly guidance.",
"可拜師(難度（DC）14): 六扇快刀+六扇心法。": "Can take as master (DC 14): Six-Door Swift Saber + Six-Door Mental Method.",
"可拜師(難度（DC）14): 禁軍槍法。": "Can take as master (DC 14): Imperial Guard Spear Art.",
"可拜師(難度（DC）14): 腐骨掌+五毒經+毒術。": "Can take as master (DC 14): Rotting-Bone Palm + Five Poisons Scripture + Poisoncraft.",
"可拜師(難度（DC）14): 藥王神針+百草心經+醫術。": "Can take as master (DC 14): Medicine King Divine Needle + Hundred-Herb Heart Sutra + Medicine.",
"可拜師(難度（DC）14): 追風掌+機關術。": "Can take as master (DC 14): Wind-Chasing Palm + Trapcraft.",
"可拜師(難度（DC）14): 追魂刀+天魔解體(禁術)。": "Can take as master (DC 14): Soul-Chasing Saber + Heavenly Demon Disintegration (Forbidden).",
"可拜師(難度（DC）16): 修羅劍+血月魔功(絕學)。": "Can take as master (DC 16): Asura Sword + Blood Moon Demon Art (Ultimate).",
"可拜師(難度（DC）16): 暴雨梨花針+千機訣+機關術。": "Can take as master (DC 16): Rainstorm Pear-Blossom Needles + Thousand-Mechanisms Art + Trapcraft.",
"可拜師(難度（DC）16): 潛行+易容。暗中觀察。": "Can take as master (DC 16): Stealth + Disguise. Observe in secret.",
"可拜師(難度（DC）18): 天劍訣+寒梅劍法。需劍意試煉。": "Can take as master (DC 18): Heavenly Sword Art + Cold Plum Sword Art. Requires Sword-Intent trial.",
"可拜師(難度（DC）18): 如來神掌+易筋經(絕學)。": "Can take as master (DC 18): Tathagata Palm + Muscle-Tendon Changing Classic (Ultimate).",
"可拜師(難度（DC）18): 索命十三式+無影訣+易容。": "Can take as master (DC 18): Life-Taking Thirteen Forms + Shadowless Art + Disguise.",
"可拜師(難度（DC）20⚠): 玄陰指+吸星大法(必有後門)。": "Can take as master (DC 20⚠): Mysterious Yin Finger + Star-Absorbing Great Method (has a backdoor).",
# ---- master-gift entries ----
"拜師禮: 修羅面具+血月教庇護令+暗紅披風(首殺後)": "Master gift: Asura Mask + Blood Moon Cult Protection Token + dark-red cape (after first kill)",
"拜師禮: 六扇門金牌(臨時)+出師: 通緝撤銷令(好感≥15)": "Master gift: Six Doors Gold Token (temporary) + graduation: Wanted-Order Revocation (favor ≥15)",
"拜師禮: 劍譜抄本(借閱)+出師禮: 承影劍(仿製)+推薦函(俠義≥40)": "Master gift: Sword-Manual copy (borrow) + graduation: Chengying Sword (replica) + recommendation letter (Heroism ≥40)",
"拜師禮: 啟動資金50兩(可分期)+四海盟貴賓卡(8折)": "Master gift: Startup fund 50 taels (installments ok) + Sihai Alliance VIP card (20% off)",
"拜師禮: 機關通訊器+機關陷阱圖紙x1+出師: VIP鑰匙": "Master gift: Mechanical communicator + trapcraft blueprint ×1 + graduation: VIP key",
"拜師禮: 毒針囊(x20)+出師: 毒術實驗室鑰匙": "Master gift: Poison-needle pouch (×20) + graduation: Poisoncraft Lab key",
"拜師禮: 無影短刃+出師禮: 免費刺殺令+易容面具(好感≥10)": "Master gift: Shadowless Short Blade + graduation: Free assassination order + disguise mask (favor ≥10)",
"拜師禮: 菩提珠(防走火+2)+出師禮: 金剛經手抄(長休+5生命值（HP）)": "Master gift: Bodhi Beads (Qi-Deviation defense +2) + graduation: handwritten Diamond Sutra (long rest +5 HP)",
"拜師禮: 藥箱(金瘡藥x5+小還丹x2)+出師禮: 蘇字招牌(賒帳20兩)": "Master gift: Medicine box (Jin Chuang Medicine ×5 + Minor Restoration Pill ×2) + graduation: Su-brand signboard (20 taels credit)",
"拜師禮: 血牙雙刀(仿製)+試煉場通行證": "Master gift: Blood-Fang Twin Sabers (replica) + trial-ground pass",
"拜師禮: 西廠腰牌+玄陰指(後門版)⚠+密檔(首殺後)": "Master gift: Western Factory waist tablet + Mysterious Yin Finger (backdoor version) ⚠ + secret file (after first kill)",
"贈禮: 烈陽劍(仿製)(精進至小有所成+好感≥10)": "Gift: Lieyang Sword (replica) (proficiency to Minor Accomplishment + favor ≥10)",
# ---- scenario strings ----
"場景：場景：唐門周邊": "Scene: Scene: Around Tang Sect",
"場景：場景：商道": "Scene: Scene: Trade Road",
"場景：場景：城市暗巷、賭坊": "Scene: Scene: City back alley, gambling house",
"場景：場景：城市街道": "Scene: Scene: City Street",
"場景：場景：天劍盟": "Scene: Scene: Tianjian Alliance",
"場景：場景：少林寺": "Scene: Scene: Shaolin Monastery",
"場景：場景：山寨大堂": "Scene: Scene: Stronghold Hall",
"場景：場景：山路、山林": "Scene: Scene: Mountain Road, Forest",
"場景：場景：沙漠、邊境": "Scene: Scene: Desert, Border",
"場景：場景：暗巷、屋頂": "Scene: Scene: Back alley, Rooftop",
"場景：場景：深山、古廟": "Scene: Scene: Deep Mountains, Ancient Temple",
"場景：場景：深山洞穴": "Scene: Scene: Deep Mountain Cave",
"場景：場景：祕密據點": "Scene: Scene: Secret Hideout",
"場景：場景：草原、北境": "Scene: Scene: Grassland, Northern Frontier",
"場景：場景：血月教據點": "Scene: Scene: Blood Moon Cult Hideout",
"場景：場景：血月教祭壇": "Scene: Scene: Blood Moon Cult Altar",
"場景：場景：衙門": "Scene: Scene: Yamen",
"場景：場景：論劍臺、酒樓": "Scene: Scene: Sword-Debate Platform, Tavern",
"場景：場景：酒館、驛站": "Scene: Scene: Wine House, Post Station",
"場景：場景：魔教總壇": "Scene: Scene: Demon Cult Main Altar",
# ---- behavior / tactic strings ----
"2-4人結陣防禦；優先保護鏢車；不主動追擊": "Form defense with 2-4 people; prioritize protecting the escort cart; do not pursue proactively",
"3-6人圍攻；一人倒下其餘難度（DC）10定力否則潰散": "Surround with 3-6 people; if one falls, the rest DC 10 Willpower or rout",
"4-8人一擁而上；頭目被擊敗或半數倒地後潰散(DC12)": "Swarm with 4-8 people; rout after leader defeated or half down (DC 12)",
"4-8人一擁而上；頭目被擊敗或半數倒地後潰散(難度（DC）12)": "Swarm with 4-8 people; rout after leader defeated or half down (DC 12)",
"三人一組包圍；配合默契(援護+2防禦)": "Surround in groups of three; good teamwork (support +2 Defense)",
"帶4-6嘍囉；優先攻擊最強者以震懾其他人": "Bring 4-6 mooks; prioritize attacking the strongest to intimidate others",
"單打獨鬥或雙人配合；利用地形掩護": "Fight solo or in pairs; use terrain cover",
"保持中距離（三步）；識招後用天劍訣破招；劍氣壓制多人": "Keep mid-range (three-step); after reading moves use Heavenly Sword Art to break; sword qi suppresses multiple",
"保持距離放暗器(三步)；被近身後換短刀": "Keep distance for hidden weapons (three-step); switch to short saber when engaged",
"近身猛攻；旋風斬羣傷；不擅長遠程對抗": "Close-range assault; Whirlwind Slash for crowd damage; weak at ranged",
"正面碾壓；咆哮降低對手士氣；無真氣不消耗招式": "Frontal crush; roar lowers opponent morale; no Qi, moves unrestricted",
"正面防守反擊；優先保護寺院；不主動追擊": "Frontal defense and counter; prioritize protecting the temple; do not pursue",
"先用魔音控制再近身吸血；對定力低的目標威脅極大": "First control with demon sound, then close in to drain blood; great threat to low-Willpower targets",
"先護體再強攻；優先壓制看起來最強的對手": "First protect body, then press attack; prioritize suppressing the strongest-looking opponent",
"以快打慢；識招破招；優先挑戰最強者": "Use speed against slow; read and break moves; prioritize challenging the strongest",
"以柔克剛；反擊為主；不主動攻擊但格擋極強": "Use softness against hardness; focus on counter; do not attack proactively but block strongly",
"不主動攻擊(除非被觸怒)；被攻擊時反擊致命；無法被偷襲": "Does not attack proactively (unless enraged); counters fatally when attacked; cannot be sneak-attacked",
"不惜代價攻擊；瀕死時使用血祭爆發": "Attack at all costs; use Blood Offering burst when dying",
"不惜自傷換取攻擊機會；數量壓制(4-6人)": "Risk self-injury for attack chances; numerical suppression (4-6 people)",
"潛行偷襲→一擊→煙霧彈脫離；從不戀戰": "Stealth ambush → one strike → smoke bomb escape; never lingers in battle",
"指揮捕快協同；優先制服而非擊殺": "Command constables in coordination; prioritize subduing rather than killing",
"所有攻擊自動識招(1/回合)；閃避+3": "All attacks auto Technique Reading (1/round); Evasion +3",
"每場戰鬥首回合自動識招一次（悟性DC12）": "Auto Technique Reading once on first round of each battle (Comprehension DC 12)",
"每失1生命值（HP）獲血怒,5點=命中+1(至多+5)": "Gain Blood Fury per HP lost; 5 points = +1 Hit (max +5)",
"魅力對抗影響NPC態度": "Charisma contest influences NPC attitude",
"纏繞目標(身法DC13脫困)": "Entangle target (Agility DC 13 to escape)",
"纏繞目標(身法難度（DC）13脫困)": "Entangle target (Agility DC 13 to escape)",
"視線-4(2回合)，脫戰檢定+2": "Sight -4 (2 rounds), disengage check +2",
"定力DC12，失敗命中-1": "Willpower DC 12, fail Hit -1",
"定力難度（DC）12，失敗命中-1": "Willpower DC 12, fail Hit -1",
"定力對抗": "Willpower contest",
"定力對抗失敗則命中-2": "Willpower contest, fail Hit -2",
"定力對抗，失敗失去次要行動": "Willpower contest, fail lose minor action",
"範圍定力難度（DC）14，失敗命中-2(1回合)": "AoE Willpower DC 14, fail Hit -2 (1 round)",
"範圍定力難度（DC）16，失敗下回合失去行動": "AoE Willpower DC 16, fail lose action next round",
"範圍中毒2d4/回合": "AoE Poison 2d4/round",
"脫戰不觸發借機": "Disengage does not trigger opportunity",
"移動+主要": "Move + major",
"移動+攻擊(自傷1d4)": "Move + attack (self-damage 1d4)",
"犧牲生命值（HP）換取命中+3(1回合)": "Sacrifice HP for Hit +3 (1 round)",
"先手檢定+2 額外移動": "Initiative check +2 extra move",
"下回合攻擊+3 (1回合)": "Attack +3 next round (1 round)",
"傷害減免+5": "Damage Reduction +5",
"防禦（DC）+3(2回合)": "Defense (DC)+3 (2 rounds)",
"隊友防禦（DC）+1(2回合)": "Ally Defense (DC)+1 (2 rounds)",
"閃避+1": "Evasion +1",
"閃避+2": "Evasion +2",
"閃避+4": "Evasion +4",
"先手+4": "Initiative +4",
"命中後威嚇": "Intimidate on hit",
"受擊後命中+1(疊加至+3)；受傷>20後效果消失": "Hit +1 after being hit (stacks to +3); effect ends after taking >20 damage",
"命中吸1d4真氣": "Hit absorbs 1d4 Qi",
"真氣恢復3/回合": "Qi recover 3/round",
"每日1次——對PC指定的單一目標造成2d6傷害": "Once per day — deal 2d6 damage to a single target designated by the PC",
"治療2d8": "Heal 2d8",
"治療2d8 HP": "Heal 2d8 HP",
"治療4d8": "Heal 4d8",
"自恢復3d6 HP": "Self-heal 3d6 HP",
"自恢復3d6 生命值（HP）": "Self-heal 3d6 HP",
"給目標疊加中毒狀態": "Apply Poisoned state to target",
"疊加中毒層數": "Stack Poison layers",
# ---- move / attack strings ----
"1d4 三步距離": "1d4 three-step range",
"1d4+身(三步距離)": "1d4+AGI (three-step range)",
"1d6+膂(-1) 使用後防禦（DC）+2": "1d6+STR(-1) Defense (DC)+2 after use",
"1d6+膂(0) 繳械": "1d6+STR(0) Disarm",
"1d8+膂 對已傷+1": "1d8+STR +1 vs injured",
"1d8+膂(+4) 先手時命中額外+1": "1d8+STR(+4) +1 extra hit on initiative",
"2d4+身(+4) 三步距離": "2d4+AGI(+4) three-step range",
"2d4+身(潛行雙倍)": "2d4+AGI (Stealth double)",
"2d6+5 三步距離": "2d6+5 three-step range",
"2d6+悟(以悟性代替膂力)": "2d6+CMP (uses Comprehension instead of Strength)",
"2d6+悟(無固定招式——每回合擇任一外功效果)": "2d6+CMP (no fixed move — choose any external-art effect each round)",
"2d6+毒(1d4/回合)": "2d6+POI(1d4/round)",
"2d6+膂": "2d6+STR",
"2d6+膂 鄰近雙目標": "2d6+STR adjacent two targets",
"2d6+膂(+4) 命中後威嚇": "2d6+STR(+4) Intimidate on hit",
"2d8 半徑2步": "2d8 radius 2 steps",
"2d8+膂": "2d8+STR",
"2d8+身": "2d8+AGI",
"2次/場": "2 uses/battle",
"3d4+5 羣體": "3d4+5 group",
"3d6+3(擊中回血傷害50%)": "3d6+3 (heal 50% of damage on hit)",
"3d6+3+中毒2d4/回合": "3d6+3 + Poison 2d4/round",
"3d6+悟": "3d6+CMP",
"3d6+悟 封脈1回合": "3d6+CMP Sealed Meridian 1 round",
"3d6+膂": "3d6+STR",
"3d6+膂(+2)": "3d6+STR(+2)",
"3d6+膂(+3)": "3d6+STR(+3)",
"3d6+身(+5) 潛行雙倍": "3d6+AGI(+5) Stealth double",
"3d8+3 半徑3步": "3d8+3 radius 3 steps",
"3d8+5 破招": "3d8+5 break move",
"3d8+膂": "3d8+STR",
"3d8+膂 先手+1d8": "3d8+STR Initiative +1d8",
"3d8+膂(+5)": "3d8+STR(+5)",
"3次/場": "3 uses/battle",
"4d6+膂(+4)": "4d6+STR(+4)",
"4d6+膂(鈍器)": "4d6+STR (blunt)",
"4d8+膂(+3)": "4d8+STR(+3)",
"4次/場": "4 uses/battle",
"4d10+膂x2 擊退3步": "4d10+STR×2 knockback 3 steps",
"5d6+10 範圍攻擊": "5d6+10 area attack",
"5d6+膂(+2)": "5d6+STR(+2)",
"1-3/次": "1-3 per use",
"1d6+身(以悟性代替膂力)": "1d6+AGI (uses Comprehension instead of Strength)",
# ---- formulas (translate realm literals; keep cell refs & structure) ----
"=B12*5+IF(F5=\"登堂入室\",5,IF(F5=\"融會貫通\",10,IF(F5=\"爐火純青\",15,IF(F5=\"登峯造極\",20,IF(F5=\"返璞歸真\",25,0)))))":
"=B12*5+IF(F5=\"Crossing the Threshold\",5,IF(F5=\"Complete Mastery\",10,IF(F5=\"Perfecting the Craft\",15,IF(F5=\"Peak of Perfection\",20,IF(F5=\"Return to Simplicity\",25,0)))))",
"=B12*5+IF(F6=\"登堂入室\",5,IF(F6=\"融會貫通\",10,IF(F6=\"爐火純青\",15,IF(F6=\"登峯造極\",20,IF(F6=\"返璞歸真\",25,0)))))":
"=B12*5+IF(F6=\"Crossing the Threshold\",5,IF(F6=\"Complete Mastery\",10,IF(F6=\"Perfecting the Craft\",15,IF(F6=\"Peak of Perfection\",20,IF(F6=\"Return to Simplicity\",25,0)))))",
"=B12*VALUE(LEFT(H5,1))+IF(F5=\"登堂入室\",3,IF(F5=\"融會貫通\",6,IF(F5=\"爐火純青\",10,IF(F5=\"登峯造極\",15,IF(F5=\"返璞歸真\",20,0)))))":
"=B12*VALUE(LEFT(H5,1))+IF(F5=\"Crossing the Threshold\",3,IF(F5=\"Complete Mastery\",6,IF(F5=\"Perfecting the Craft\",10,IF(F5=\"Peak of Perfection\",15,IF(F5=\"Return to Simplicity\",20,0)))))",
"=B12*VALUE(LEFT(H5,1))+IF(F6=\"登堂入室\",3,IF(F6=\"融會貫通\",6,IF(F6=\"爐火純青\",10,IF(F6=\"登峯造極\",15,IF(F6=\"返璞歸真\",20,0)))))":
"=B12*VALUE(LEFT(H5,1))+IF(F6=\"Crossing the Threshold\",3,IF(F6=\"Complete Mastery\",6,IF(F6=\"Perfecting the Craft\",10,IF(F6=\"Peak of Perfection\",15,IF(F6=\"Return to Simplicity\",20,0)))))",
"=B12*VALUE(LEFT(H6,1))+IF(F6=\"登堂入室\",3,IF(F6=\"融會貫通\",6,IF(F6=\"爐火純青\",10,IF(F6=\"登峯造極\",15,IF(F6=\"返璞歸真\",20,0)))))":
"=B12*VALUE(LEFT(H6,1))+IF(F6=\"Crossing the Threshold\",3,IF(F6=\"Complete Mastery\",6,IF(F6=\"Perfecting the Craft\",10,IF(F6=\"Peak of Perfection\",15,IF(F6=\"Return to Simplicity\",20,0)))))",
"=B12*VALUE(LEFT(H8,1))+IF(F6=\"登堂入室\",3,IF(F6=\"融會貫通\",6,IF(F6=\"爐火純青\",10,IF(F6=\"登峯造極\",15,IF(F6=\"返璞歸真\",20,0)))))":
"=B12*VALUE(LEFT(H8,1))+IF(F6=\"Crossing the Threshold\",3,IF(F6=\"Complete Mastery\",6,IF(F6=\"Perfecting the Craft\",10,IF(F6=\"Peak of Perfection\",15,IF(F6=\"Return to Simplicity\",20,0)))))",
# ---- martial-arts move / technique names ----
"兩儀劍法": "Two-Forms Sword Art",
"先天功": "Pre-Heaven Art",
"伏魔杖法": "Demon-Subduing Staff Art",
"凌波微步": "Lingbo Step",
"六扇刀法": "Six-Door Saber Art",
"六扇心法": "Six-Door Mental Method",
"六扇快刀": "Six-Door Swift Saber",
"六扇快刀·快刀緝捕": "Six-Door Swift Saber · Quick-Arrest Cut",
"千機訣·推演": "Thousand-Mechanisms Art · Deduction",
"千機訣": "Thousand-Mechanisms Art",
"五毒經": "Five Poisons Scripture",
"五虎斷門刀·劈風式": "Five Tigers Door-Cutting Saber · Wind-Splitting Form",
"劈風": "Wind-Splitting",
"修羅劍·滅": "Asura Sword · Annihilation",
"修羅劍": "Asura Sword",
"滅": "Annihilation",
"九針渡穴": "Nine Needles to Cross Acupoints",
"三星照月": "Three Stars Mirror the Moon",
"劍宗(華山)": "Sword Sect (Huashan)",
"劍宗心法": "Sword Sect Mental Method",
"唐門暗器": "Tang Sect Hidden Weapon",
"噬血魔功": "Blood-Devouring Demon Art",
"天劍心經": "Heavenly Sword Heart Sutra",
"天劍訣": "Heavenly Sword Art",
"天劍訣·萬劍歸宗": "Heavenly Sword Art · Ten Thousand Swords Return to Origin",
"天魔解體": "Heavenly Demon Disintegration",
"太極": "Taiji",
"太極拳": "Taiji Fist",
"如來": "Tathagata",
"如來神掌": "Tathagata Palm",
"寒梅劍法·霜寒劍氣": "Cold Plum Sword Art · Frosty Sword Qi",
"霜寒劍氣": "Frosty Sword Qi",
"幻陰步": "Illusion-Yin Step",
"影宗(逍遙)": "Shadow Sect (Xiaoyao)",
"忘川樓": "Wangchuan Tower",
"快劍十三式": "Thirteen Forms of Swift Sword",
"散人": "Independent",
"散修掌法": "Independent Cultivator Palm Art",
"旋風斬": "Whirlwind Slash",
"易筋經": "Muscle-Tendon Changing Classic",
"曹少欽": "Cao Shaoqin",
"流氓拳": "Hooligan Fist",
"殘陽斬": "Setting-Sun Slash",
"機宗(丐幫)": "Skill Sect (Beggar Sect)",
"機關陷阱": "Mechanical Trap",
"橫掃": "Sweep",
"棒打惡犬": "Strike the Vicious Dog",
"毒宗(唐門)": "Poison Sect (Tang Sect)",
"毒掌": "Poison Palm",
"毒霧(瀕死)": "Poison Mist (Dying)",
"氣宗(武當)": "Qi Sect (Wudang)",
"猛": "Fierce",
"無影訣": "Shadowless Art",
"無招": "No Form",
"無門派(山賊)": "No Sect (Mountain Bandit)",
"玄陰": "Mysterious Yin",
"玄陰指": "Mysterious Yin Finger",
"玄陰指（空手）": "Mysterious Yin Finger (Unarmed)",
"狂沙刀法": "Mad Sand Saber Art",
"狼羣召喚": "Wolf Pack Summon",
"獨孤九劍·破劍式": "Dugu Nine Swords · Breaking the Sword",
"獸王之血": "Beast King's Blood",
"破劍式": "Breaking the Sword",
"碎山": "Mountain Shatter",
"碎山斬": "Mountain-Shattering Slash",
"禁術": "Forbidden Art",
"禁軍槍法·槍出遊龍": "Imperial Guard Spear Art · Spear Like a Roaming Dragon",
"禁軍槍法·橫掃千軍": "Imperial Guard Spear Art · Sweep Across the Army",
"白虹貫日": "White Rainbow Pierces the Sun",
"百草心經": "Hundred-Herb Heart Sutra",
"索命": "Life-Taking",
"索命十三式": "Life-Taking Thirteen Forms",
"純陽心法": "Pure Yang Mental Method",
"絕學": "Ultimate Art",
"羅漢拳": "Arhat Fist",
"自創步法": "Self-Created Footwork",
"華山劍法": "Huashan Sword Art",
"萬佛寺": "Wanfo Temple",
"萬劍歸宗": "Ten Thousand Swords Return to Origin",
"藥王神針": "Medicine King Divine Needle",
"藥王谷": "Yaowang Valley",
"藥王谷(叛)": "Yaowang Valley (Defected)",
"藥王針法": "Medicine King Needle Art",
"蝕骨": "Bone-Eroding",
"蠻族": "Barbarian",
"血影步": "Blood Shadow Step",
"血影步·幻": "Blood Shadow Step · Illusion",
"血月大法": "Blood Moon Great Method",
"血月拳": "Blood Moon Fist",
"血月教": "Blood Moon Cult",
"血月魔刀": "Blood Moon Demon Saber",
"血月魔功": "Blood Moon Demon Art",
"血祭": "Blood Offering",
"黃泉步": "Yellow Springs Step",
"西廠": "Western Factory",
"金刀帖": "Gold Saber Invitation",
"金剛不壞體": "Indestructible Vajra Body",
"金剛宗(少林)": "Vajra Sect (Shaolin)",
"金剛心法": "Vajra Mental Method",
"金剛怒目": "Vajra's Furious Gaze",
"金針止血": "Gold Needle Stanch Bleeding",
"銅人陣": "Bronze Figure Formation",
"鐵掌": "Iron Palm",
"鐵面刀法": "Iron-Faced Saber Art",
"鐵面無私": "Iron-Faced and Impartial",
"遊龍": "Roaming Dragon",
"遠程掩護（被動）": "Ranged Cover (Passive)",
"追風": "Wind Chasing",
"追風掌": "Wind-Chasing Palm",
"追魂": "Soul-Chasing",
"追魂刀": "Soul-Chasing Saber",
"逍遙心法": "Xiaoyao Mental Method",
"輕身術": "Light-Body Art",
"雙拳": "Both Fists",
"難度（DC）10": "DC 10",
"難度（DC）11": "DC 11",
"難度（DC）12": "DC 12",
"難度（DC）13": "DC 13",
"難度（DC）14": "DC 14",
"難度（DC）15": "DC 15",
"難度（DC）16": "DC 16",
"難度（DC）17": "DC 17",
"難度（DC）18": "DC 18",
"難度（DC）21": "DC 21",
# ---- equipment / weapons / armor / items ----
"僧袍": "Monk Robe",
"儒衫": "Scholar Robe",
"墨綠長袍": "Dark Green Long Robe",
"暗紅長袍": "Dark Red Long Robe",
"灰布長衫": "Gray Cloth Long Gown",
"灰色旅裝": "Gray Travel Outfit",
"皮甲": "Leather Armor",
"皮甲+披風": "Leather Armor + Cape",
"硬皮甲": "Hard Leather Armor",
"破布衣": "Tattered Cloth Robe",
"粗布衣": "Coarse Cloth Robe",
"紅布衣": "Red Cloth Robe",
"布衣+護腕": "Cloth Robe + Vambrace",
"破舊匕首(1d4)": "Worn Dagger (1d4)",
"短刀(1d6)": "Short Saber (1d6)",
"制式單刀(1d8)": "Standard Single Saber (1d8)",
"制式官刀(1d8+1)": "Standard Official Saber (1d8+1)",
"劣質單刀(1d8)": "Inferior Single Saber (1d8)",
"名劍(1d8+2)": "Famed Sword (1d8+2)",
"大砍刀 (2d6)": "Cleaver (2d6)",
"大漠彎刀(1d8+2)": "Desert Curved Saber (1d8+2)",
"官刀(1d8+1)": "Official Saber (1d8+1)",
"官制長刀 (1d8+2)": "Official Long Saber (1d8+2)",
"巨斧(2d8)": "Great Axe (2d8)",
"巨型戰錘 (4d10)": "Giant War Hammer (4d10)",
"裂地斧": "Earth-Rending Axe",
"鐵劍(1d8)": "Iron Sword (1d8)",
"長刀(1d8)": "Long Saber (1d8)",
"齊眉棍(1d6+1)": "Brows-Level Staff (1d6+1)",
"血刃(2d6+1)": "Blood Blade (2d6+1)",
"血紋彎刀(2d4)": "Blood-Pattern Curved Saber (2d4)",
"淬毒短刃(1d6+毒)": "Poison-Coated Short Blade (1d6+POI)",
"無(空手)": "None (Unarmed)",
"無名掌": "Nameless Palm",
"無影短刃": "Shadowless Short Blade",
"無影短刃(1d6+身)": "Shadowless Short Blade (1d6+AGI)",
"烈陽劍（仿製·1d8+1）": "Lieyang Sword (Replica · 1d8+1)",
"精鋼單刀(1d8+1)": "Fine Steel Single Saber (1d8+1)",
"精鋼長劍(1d8+1)": "Fine Steel Long Sword (1d8+1)",
"禁軍長槍(1d10)": "Imperial Guard Long Spear (1d10)",
"禁軍長槍（1d10）+ 禁軍輕甲（減免2）": "Imperial Guard Long Spear (1d10) + Imperial Guard Light Armor (Reduction 2)",
"飛石": "Flying Stone",
"飛針囊(暗器x20)": "Flying Needle Pouch (hidden weapon ×20)",
"煙霧彈": "Smoke Bomb",
"煙霧彈/毒煙/繩網(預埋5個)": "Smoke Bomb / Poison Smoke / Rope Net (5 pre-placed)",
"金瘡藥×3（戰鬥外可給PC使用）": "Jin Chuang Medicine ×3 (usable on PC outside combat)",
"六扇門官服": "Six Doors Official Robe",
"官服": "Official Robe",
"文官袍": "Civil Official Robe",
"舊官服": "Old Official Robe",
"蟒袍": "Python Robe",
"錦緞長袍": "Brocade Long Robe",
"素衣": "Plain Robe",
"夜行衣": "Night-Cloak",
"黑行衣": "Black Action Garb",
"黑袍+面具": "Black Robe + Mask",
"深色勁裝": "Dark Tight Outfit",
"血色戰袍": "Blood-Colored War Robe",
"獸皮護甲": "Beast-Hide Armor",
"獸骨戰甲": "Beast-Bone Battle Armor",
"獸骨護甲+毛皮": "Beast-Bone Armor + Fur",
"禁軍輕甲(減免2)": "Imperial Guard Light Armor (Reduction 2)",
"魔杖": "Demon Staff",
"魔音攝魂": "Demon Sound Captures Soul",
"魔功護體": "Demon Art Bodyguard",
"魔教外圍教徒": "Demon Cult Outer Disciple",
"魔教護法": "Demon Cult Guardian",
"回春訣": "Spring-Return Art",
"叫化心法": "Beggar's Mental Method",
"召喚2道劍氣輔助攻擊(每道1d6+2)": "Summon 2 sword-qi to assist attacks (each 1d6+2)",
"召喚3隻幽靈狼(生命值（HP）20)": "Summon 3 ghost wolves (HP 20)",
"召喚金刀衛護衛": "Summon Gold-Saber Guard",
"召喚銅人護盾": "Summon Bronze-Figure Shield",
"大地咆哮": "Earth Roar",
"戰爭咆哮": "War Cry",
"天榜#8。第四境數據用於劇本第二章洛陽。": "Heaven Ranking #8. Fourth Realm data used in Act 2 Luoyang of the script.",
"護鏢陣勢": "Escort Defense Formation",
"趟子手刀法": "Porter Saber Art",
"踏雪無痕": "Treading Snow Without Trace",
"鐵山": "Tieshan",
"反擊式": "Counter Style",
"格擋成功後自動反擊1d8": "Auto counter 1d8 after successful block",
"反應": "Reaction",
"心眼": "Mind's Eye",
"肌肉力量、爆發力": "Muscle power, explosiveness",
"速度、靈活、輕功": "Speed, flexibility, lightfoot",
"經脈承載、體質、生命韌性": "Meridian capacity, physique, life toughness",
"武學領悟力、學習效率": "Martial comprehension, learning efficiency",
"意志力、心境穩定": "Willpower, mental stability",
"人格魅力、人際影響力": "Personal charm, interpersonal influence",
"-- 基本資料 --": "-- Basic Info --",
"-- 六維屬性 --": "-- Six Attributes --",
"-- 衍生值 --": "-- Derived Values --",
"-- 裝備 --": "-- Equipment --",
"-- 技能（簡化） --": "-- Skills (Simplified) --",
"-- 招式與能力 --": "-- Moves & Abilities --",
"-- 持有物品 --": "-- Possessions --",
"敵人": "Enemy",
"角色卡": "Character Card",
"陸沉淵": "Lu Chenyuan",
"3(正宗)": "3 (Orthodox)",
"2(入門)": "2 (Initiate)",
"5(絕世)": "5 (Peerless)",
"腐骨掌": "Rotting-Bone Palm",
"推演": "Deduction",
"暴雨梨花針": "Rainstorm Pear-Blossom Needles",
"範圍攻擊": "Area Attack",
"PC在柳生煙相鄰時，瀕死檢定DC-2": "When the PC is adjacent to Liu Shengyan, Dying check DC -2",
"同伴規則見20_單人規則.md §4。不消耗真氣——改為招式使用次數限制。": "Companion rules see 20_單人規則.md §4. Does not consume Qi — instead move uses are limited.",
"烈陽劍法·烈日焚天": "Lieyang Sword Art · Scorching Sun Burns the Sky",
"烈日": "Scorching Sun",
"烈日焚天": "Scorching Sun Burns the Sky",
"烈陽心經": "Lieyang Heart Sutra",
"朝廷·禮部": "Court · Ministry of Rites",
"無": "None",
"緝捕": "Arrest",
"成名劍客，在江湖上有一定名氣。": "A famed swordsman with some renown in the jianghu.",
"打狗棒法": "Dog-Beating Staff",
"緝捕鎖鏈": "Arrest Chain",
"吸星大法·殘篇": "Star-Absorbing Great Method · Fragment",
"吸星": "Star-Absorbing",
"潛行雙倍2d6+身": "Stealth double 2d6+AGI",
"偽裝為任意同體型者": "Disguise as any same-size person",
"攬雀尾": "Grasping the Sparrow's Tail",
"漫天花雨": "Rain of Flowers",
"北方草原的精英戰士，力量驚人。": "Elite warrior of the northern grasslands, astonishing strength.",
}

# ---- TERM fallback (longest first) for any token not in EXACT ----
TERM = [
("膂力","Strength"),("身法","Agility"),("根骨","Constitution"),("悟性","Comprehension"),
("定力","Willpower"),("魅力","Charisma"),
("膂","STR"),("身","AGI"),("悟","CMP"),("定","WIL"),("魅","CHA"),("根","CON"),("毒","POI"),
("生命值（HP）","HP"),("生命值","HP"),("真氣","Qi"),("先手","Initiative"),("閃避","Evasion"),
("防禦（DC）","Defense (DC)"),("防禦","Defense"),("難度（DC）","DC"),("難度","DC"),
("命中","Hit"),("威嚇","Intimidate"),("傷害","Damage"),("效果","Effect"),("範圍","Range"),
("封脈","Sealed Meridian"),("中毒","Poison"),("回合","round"),("次/場","uses/battle"),
("三步","three-step"),("距離","range"),("半徑","radius"),("遠處","far"),
("門派","Sect"),("境界","Realm"),("內功","Internal Art"),("外功","External Art"),
("輕功","Lightfoot"),("劍法","Sword Art"),("刀法","Saber Art"),("拳掌","Fist & Palm"),
("棍法","Staff Art"),("槍法","Spear Art"),("暗器","Hidden Weapon"),("毒術","Poisoncraft"),
("醫術","Medicine"),("易容","Disguise"),("丹術","Alchemy"),("機關術","Trapcraft"),
("武功","Martial Art"),("招式","Move"),("技能","Skills"),("屬性","Attribute"),
("六扇門","Six Doors"),("天劍盟","Tianjian Alliance"),("血月教","Blood Moon Cult"),
("唐門","Tang Sect"),("少林","Shaolin"),("丐幫","Beggar Sect"),("藥王谷","Yaowang Valley"),
("太虛宮","Taixu Palace"),("萬佛寺","Wanfo Temple"),("西廠","Western Factory"),
("千機閣","Qianji Pavilion"),("四海盟","Sihai Alliance"),("忘川樓","Wangchuan Tower"),
("逍遙","Xiaoyao"),("影宗","Shadow Sect"),("劍宗","Sword Sect"),("氣宗","Qi Sect"),
("武當","Wudang"),("華山","Huashan"),("禁軍","Imperial Guard"),("朝廷","Court"),
("北境","Northern Frontier"),("西域","Western Regions"),("草原","Grassland"),
("山寨","Stronghold"),("血祭","Blood Offering"),("狂暴","Berserk"),("絕學","Ultimate Art"),
("禁術","Forbidden Art"),("修羅","Asura"),("血月","Blood Moon"),("血影","Blood Shadow"),
("天劍","Heavenly Sword"),("烈陽","Lieyang"),("寒梅","Cold Plum"),("霜寒","Frosty"),
("玄陰","Mysterious Yin"),("易筋","Muscle-Tendon"),("金剛","Vajra"),("羅漢","Arhat"),
("暴雨","Rainstorm"),("梨花","Pear-Blossom"),("索命","Life-Taking"),("追魂","Soul-Chasing"),
("追風","Wind-Chasing"),("碎山","Mountain-Shatter"),("旋風","Whirlwind"),("殘陽","Setting-Sun"),
("鐵面","Iron-Faced"),("白鶴","Baihe"),("朱雀","Zhuque"),("孟婆","Meng Po"),
("柳如風","Liu Rufeng"),("柳生煙","Liu Shengyan"),("段天涯","Duan Tianya"),
("蘇青囊","Su Qingnang"),("沈萬金","Shen Wanjin"),("紫陽","Ziyang"),("慧覺","Huijue"),
("清虛","Qingxu"),("楚懷沙","Chu Huaisha"),("燕飛雲","Yan Feiyun"),("金日磾","Jin Ridi"),
("鐵山","Tieshan"),("鐵鏡心","Tie Jingxin"),("韓豹","Han Bao"),("韓鐵衣","Han Tieyi"),
("趙無極","Zhao Wuji"),("曹少欽","Cao Shaoqin"),("蘇小妹","Su Xiaomei"),("南宮晦","Nangong Hui"),
("包小乙","Bao Xiaoyi"),("公輸玄","Gongshu Xuan"),("墨染","Mo Ran"),("厲殘陽","Li Canyang"),
("夜修羅","Ye Xiuluo"),("山賊","Bandit"),("嘍囉","Mook"),("頭目","Chief"),
("刀客","Saber Master"),("老怪","Old Eccentric"),("散修","Independent Cultivator"),
("同伴","Companion"),("長老","Elder"),("捕快","Constable"),("堂主","Bureau Chief"),
("勇士","Warrior"),("武僧","Monk"),("外圍弟子","Outer Disciple"),("劍客","Swordsman"),
("刺客","Assassin"),("潑皮","Hooligan"),("弟子","Disciple"),("教主","Cult Leader"),
("護法","Guardian"),("精英教徒","Elite Disciple"),("核心高層","Core High-Ranking"),
("中層","Mid-level"),("底層","Lowest-Tier"),("大護法","Grand Guardian"),
("·"," · "),
]

def translate(v):
    if not isinstance(v, str):
        return v
    if FILE_REF.search(v):
        return v  # keep filename/path refs exactly
    if v in EXACT:
        return EXACT[v]
    out = v
    for zh, en in TERM:
        if zh in out:
            out = out.replace(zh, en)
    return out

def translate_title(t):
    if not isinstance(t, str) or not CJK.search(t):
        return t
    if t in EXACT:
        return EXACT[t]
    out = t
    for zh, en in TERM:
        if zh in out:
            out = out.replace(zh, en)
    return out

def main():
    total_cells = 0
    for fn in FILES:
        src = os.path.join(CN, fn)
        dst = os.path.join(EN, fn)
        wb = openpyxl.load_workbook(src, data_only=False)
        for ws in wb.worksheets:
            ws.title = translate_title(ws.title)[:31]
            for row in ws.iter_rows():
                for c in row:
                    if isinstance(c.value, str) and CJK.search(c.value):
                        newv = translate(c.value)
                        c.value = newv
                        total_cells += 1
        wb.save(dst)
    print("FILES_WRITTEN", len(FILES))
    print("STRING_CELLS_TRANSLATED", total_cells)

if __name__ == "__main__":
    main()
