# -*- coding: utf-8 -*-
"""
Translate Dead by Daylight TRPG map YAML + SVG files from Chinese to English.
Strategy: format-agnostic, value-level dictionary replacement.
 - YAML: extract each field value (block & flow styles) and translate as a unit.
 - SVG: extract each <text> content and translate as a unit.
All keys, numbers, coordinates, and code fields are preserved exactly.
"""
import re, glob, os, sys

SRC = r"J:\Buddycode\2026-06-21-13-01-27\rules_source\中文\黎明殺機TRPG\maps"
DST = r"J:\Buddycode\2026-06-21-13-01-27\rules_source\英文\黎明殺機TRPG\maps"
os.makedirs(DST, exist_ok=True)

# ---------------------------------------------------------------------------
# TR: exact full-string entries (highest priority). Keys are the CHINESE
# strings as they appear in source; values are the English translation.
# Full-width parens are converted to ASCII in the values for cleanliness.
# ---------------------------------------------------------------------------
TR = {}

# ---- Realm names (meta.realm) ----
TR["麥克米蘭莊園（MacMillan Estate, R1）"] = "Macmillan Estate (R1)"
TR["廢車場（Autohaven Wreckers, R2）"] = "Autohaven Wreckers (R2)"
TR["寒風農場（Coldwind Farm, R3）"] = "Coldwind Farm (R3)"
TR["克羅特斯精神病院（Crotus Prenn Asylum, R4）"] = "Crotus Prenn Asylum (R4)"
TR["死水沼澤（Backwater Swamp, R5）"] = "Backwater Swamp (R5)"
TR["雷利紀念研究所（Léry's Memorial Institute, R6）"] = "Léry's Memorial Institute (R6)"
TR["血紅森林（Red Forest, R7）"] = "Red Forest (R7)"
TR["遺棄骨場（Forsaken Boneyard, R8）"] = "Forsaken Boneyard (R8)"
TR["寒風農場（Coldwind Farm, R3） → 霧窖（Fog Cellar）"] = "Coldwind Farm (R3) → Fog Cellar"
TR["死水沼澤（Backwater Swamp, R5） → 虛空（The Void） → 隱室（Hidden Workshop）"] = "Backwater Swamp (R5) → The Void → Hidden Workshop"
TR["遺棄骨場（Forsaken Boneyard, R8） → 孤塔（Lone Tower） → 無名之心（The Nameless Heart）"] = "Forsaken Boneyard (R8) → Lone Tower → The Nameless Heart"
# bare realm (used in names/regions)
TR["麥克米蘭莊園"] = "Macmillan Estate"
TR["廢車場"] = "Autohaven Wreckers"
TR["寒風農場"] = "Coldwind Farm"
TR["克羅特斯精神病院"] = "Crotus Prenn Asylum"
TR["死水沼澤"] = "Backwater Swamp"
TR["雷利紀念研究所"] = "Léry's Memorial Institute"
TR["血紅森林"] = "Red Forest"
TR["遺棄骨場"] = "Forsaken Boneyard"

# ---- Region names (Chinese part -> English, keep code) ----
TR["外圍林地（outer_woods）"] = "Outer Woods (outer_woods)"
TR["中央廠區（central_works）"] = "Central Works (central_works)"
TR["礦坑區（pit_area）"] = "Pit Area (pit_area)"
TR["南場（yard_south）"] = "South Yard (yard_south)"
TR["北場（yard_north）"] = "North Yard (yard_north)"
TR["鐵谷（canyon）"] = "Canyon (canyon)"
TR["田區（fields）"] = "Fields (fields)"
TR["建物區（buildings）"] = "Buildings (buildings)"
TR["林地（forest）"] = "Forest (forest)"
TR["核心區（core）"] = "Core (core)"
TR["沼澤（swamp）"] = "Swamp (swamp)"
TR["無名之心（heart）"] = "The Nameless Heart (heart)"
TR["病房區（ward）"] = "Ward (ward)"
TR["禮拜堂區（chapel）"] = "Chapel (chapel)"
TR["病歷區（records）"] = "Records (records)"
TR["神殿一層（temple_1）"] = "Temple 1F (temple_1)"
TR["神殿二層（temple_2）"] = "Temple 2F (temple_2)"
TR["神殿三層（temple_3）"] = "Temple 3F (temple_3)"
TR["孤塔（tower）"] = "Lone Tower (tower)"
TR["虛空（void）"] = "The Void (void)"
TR["隱室（workshop）"] = "Hidden Workshop (workshop)"
TR["霧窖（cellar）"] = "Fog Cellar (cellar)"
TR["骨場地表（boneyard）"] = "Boneyard Surface (boneyard)"
TR["A 翼（wing_a）"] = "Wing A (wing_a)"
TR["B 翼（wing_b）"] = "Wing B (wing_b)"
# bare region (Chinese only)
TR["外圍林地"] = "Outer Woods"
TR["中央廠區"] = "Central Works"
TR["礦坑區"] = "Pit Area"
TR["南場"] = "South Yard"
TR["北場"] = "North Yard"
TR["鐵谷"] = "Canyon"
TR["田區"] = "Fields"
TR["建物區"] = "Buildings"
TR["林地"] = "Forest"
TR["核心區"] = "Core"
TR["沼澤"] = "Swamp"
TR["無名之心"] = "The Nameless Heart"
TR["病房區"] = "Ward"
TR["禮拜堂區"] = "Chapel"
TR["病歷區"] = "Records"
TR["神殿一層"] = "Temple 1F"
TR["神殿二層"] = "Temple 2F"
TR["神殿三層"] = "Temple 3F"
TR["孤塔"] = "Lone Tower"
TR["虛空"] = "The Void"
TR["隱室"] = "Hidden Workshop"
TR["霧窖"] = "Fog Cellar"
TR["骨場地表"] = "Boneyard Surface"
TR["A 翼"] = "Wing A"
TR["B 翼"] = "Wing B"

# ---- Type taxonomy ----
TR["入口"] = "Entrance"
TR["出口"] = "Exit"
TR["主建物"] = "Main Building"
TR["開闊區"] = "Open Area"
TR["開闊"] = "Open"
TR["地標"] = "Landmark"
TR["制高點"] = "Vantage Point"
TR["特殊"] = "Special"
TR["通道"] = "Passage"
TR["可選"] = "Optional"
TR["寶箱（Chest）"] = "Chest"
TR["建物層"] = "Building Level"
TR["建物內"] = "Building Interior"
TR["房間"] = "Room"
TR["樞紐"] = "Hub"
TR["關鍵"] = "Key"
TR["死路"] = "Dead End"
TR["危險"] = "Hazard"
TR["殘影"] = "Afterimage"
TR["神殿"] = "Temple"
TR["孤塔"] = "Lone Tower"
TR["無名之心"] = "The Nameless Heart"
TR["掩體區"] = "Cover Zone"
TR["掩體地標"] = "Cover Landmark"
TR["主區"] = "Main Zone"
TR["主地標"] = "Main Landmark"
TR["主場"] = "Main Arena"
TR["遮蔽區"] = "Concealment Zone"
TR["關鍵地標"] = "Key Landmark"
TR["領域"] = "Realm"
TR["第三幕"] = "Act 3"
TR["終局"] = "Endgame"
TR["營火"] = "Campfire"
TR["裂隙"] = "Rift"
TR["逃生門（Exit Gate）"] = "Exit Gate"
TR["逃脫"] = "Escape"
TR["迷霧通道"] = "Mist Corridor"
TR["隱門"] = "Hidden Door"
TR["根道"] = "Root Passage"
TR["檔案通道"] = "Archive Passage"
TR["同源臍帶"] = "Shared Umbilical"
TR["最初的根"] = "First Root"
TR["攀升"] = "Ascent"
TR["下沉通道"] = "Sink Passage"
TR["下探"] = "Descent"
TR["滲透"] = "Seep"
TR["虛空漂移"] = "Void Drift"
TR["霧縫"] = "Mist Rift"
TR["領域關係圖（拓撲）"] = "Realm Relation Map (Topology)"
# type with 刻痕 (notch)
TR["制高點／刻痕5"] = "Vantage Point / Notch 5"
TR["地標／刻痕1"] = "Landmark / Notch 1"
TR["地標／刻痕2"] = "Landmark / Notch 2"
TR["地標／刻痕4"] = "Landmark / Notch 4"
TR["可選／刻痕8"] = "Optional / Notch 8"
TR["特殊／刻痕6"] = "Special / Notch 6"
TR["通道／刻痕3"] = "Passage / Notch 3"
# compound object types (already-bearing English)
TR["岩石（半掩體）"] = "Rock (Half-Cover)"
TR["樹叢（遮蔽）"] = "Brush (Concealment)"
TR["板子（Pallet）"] = "Pallet"
TR["窗戶（Window）"] = "Window"
TR["置物櫃（Locker）"] = "Locker"
TR["掛鉤（Hook）"] = "Hook"
TR["臍帶（Umbilical）"] = "Umbilical"
TR["泥像陷阱（Mud Glyph）"] = "Mud Glyph Trap"
TR["泥像陷阱（Mud Glyph）埋伏點"] = "Mud Glyph Trap (Ambush Point)"
TR["浮腫者（RC-06）巡邏點"] = "The Bloated (RC-06) Patrol Point"
TR["灰咽（RC-05）巡邏點"] = "Ash Throat (RC-05) Patrol Point"
TR["穗行者（RC-04）埋伏點"] = "The Stalk-row Walker (RC-04) Ambush Point"
TR["巨樹（唯一防護，阻擋投擲）"] = "Giant Tree (Sole Cover; blocks thrown objects)"
TR["母之居（掩體）"] = "Mother's Dwelling (Cover)"
TR["東石雕群（掩體）"] = "East Statue Cluster (Cover)"
TR["西石雕群（掩體）"] = "West Statue Cluster (Cover)"
TR["烏鴉巢（掩體）"] = "Crow's Nest (Cover)"
TR["廢車堆（掩體）"] = "Wreck Pile (Cover)"
TR["廢車牆（掩體）"] = "Wreck Wall (Cover)"
TR["屠宰台（掩體）"] = "Slaughter Table (Cover)"
TR["手術台（低掩體）"] = "Operating Table (Low Cover)"
TR["病床（掩體）"] = "Hospital Bed (Cover)"
TR["病房隔牆（可閃現穿越）"] = "Ward Partition (Blink-passable)"
TR["病房隔簾（半掩體）"] = "Ward Curtain (Half-Cover)"
TR["病歷架（掩體）"] = "Records Rack (Cover)"
TR["石像圈（關鍵，可致辭）"] = "Stone Statue Circle (Key; can be addressed)"
TR["石柱（掩體）"] = "Stone Pillar (Cover)"
TR["貨架（掩體）"] = "Shelf (Cover)"
TR["走廊隔牆（不可通行）"] = "Corridor Partition (Impassable)"
TR["牆體（不可通行）"] = "Wall (Impassable)"
TR["塔緣矮牆（不可通行外緣）"] = "Tower-edge Low Wall (Impassable outer edge)"
TR["鐵谷崖壁（不可通行）"] = "Canyon Cliff (Impassable)"
TR["外牆裂縫（第三幕後逃出點）"] = "Outer Wall Crack (Escape point after Act 3)"
TR["破洞地板（墜落風險）"] = "Broken Floor (Fall risk)"
TR["天穹裂口（hr_rift 入口）"] = "Sky-roof Rift (hr_rift entrance)"
TR["唯一門（單向，護士堵門）"] = "Only Door (One-way; Nurse blocks it)"
TR["沉沒階（下層入口）"] = "Sunken Stair (Lower entrance)"
TR["木棧（安全地面）"] = "Wooden Pier (Safe ground)"
TR["玉米田（視線遮蔽）"] = "Cornfield (Line-of-sight concealment)"
TR["玉米田（視線遮蔽，留撥動痕跡 2 輪）"] = "Cornfield (Line-of-sight concealment; leaves sway marks 2 rounds)"
TR["深水（危險）"] = "Deep Water (Hazard)"
TR["深水（危險，移動減速，每段檢定）"] = "Deep Water (Hazard; movement slowed; check per segment)"
TR["淺水（可佈泥像陷阱）"] = "Shallow Water (Mud Glyph Traps may be placed)"
TR["紅葉海（瀕死爬行完全隱蔽）"] = "Red Leaf Sea (Dying-crawl fully concealed)"
TR["蘆葦（視線遮蔽）"] = "Reed (Line-of-sight concealment)"
TR["觀察窗（可翻越）"] = "Observation Window (Climbable)"
TR["觀眾席階梯（不可通行外緣）"] = "Auditorium Stairs (Impassable outer edge)"
TR["不穩車堆（觸發坍塌）"] = "Unstable Car Pile (Triggers collapse)"
TR["塔門（需第一顆餘燼）"] = "Tower Door (Requires first Ember)"
TR["吊肉鉤架（掩體）"] = "Meat-hook Rack (Cover)"
TR["分類誤判"] = "Misclassification"
TR["錯階（回頭走會多一階，錯誤比例）"] = "Misaligned Stairs (Backtracking adds a step; wrong ratio)"
TR["A 翼房間（掩體）"] = "Wing A Room (Cover)"
TR["B 翼房間（掩體）"] = "Wing B Room (Cover)"
TR["A 翼隔牆（不可通行）"] = "Wing A Partition (Impassable)"
TR["隱門"] = "Hidden Door"
TR["暗渠"] = "Drainage Channel"

# ---- Edge channel ----
TR["上升"] = "Ascend"
TR["下沉（單向）"] = "Sink (One-way)"
TR["下行梯"] = "Descending Ladder"
TR["下行階"] = "Descending Stairs"
TR["分類誤判（單向）"] = "Misclassification (One-way)"
TR["單門"] = "Single Door"
TR["單面鏡窗"] = "One-way Mirror Window"
TR["地板格柵"] = "Floor Grate"
TR["塔門"] = "Tower Door"
TR["室內"] = "Interior"
TR["室內門"] = "Interior Door"
TR["室外"] = "Exterior"
TR["密道"] = "Secret Passage"
TR["懸垂根"] = "Hanging Root"
TR["攀爬"] = "Climb"
TR["暗渠"] = "Drainage Channel"
TR["暗門"] = "Secret Door"
TR["木棧"] = "Wooden Pier"
TR["根道（第三幕）"] = "Root Passage (Act 3)"
TR["樓梯"] = "Stairs"
TR["沙地"] = "Sand"
TR["涉水"] = "Wade"
TR["深水"] = "Deep Water"
TR["無方向"] = "No Direction"
TR["無盡階"] = "Endless Stair"
TR["石廊"] = "Stone Corridor"
TR["石門"] = "Stone Door"
TR["破口"] = "Breach"
TR["穿越"] = "Cross"
TR["窄道"] = "Narrow Path"
TR["窄門"] = "Side Door"
TR["窗戶（Window）／跳下"] = "Window / Drop"
TR["紅葉海"] = "Red Leaf Sea"
TR["臍帶（Umbilical）"] = "Umbilical"
TR["落葉地"] = "Fallen Leaves"
TR["虛空漂移"] = "Void Drift"
TR["螺旋梯"] = "Spiral Stair"
TR["裂隙"] = "Rift"
TR["視線"] = "Line of Sight"
TR["跳下（單向）"] = "Drop (One-way)"
TR["遮蔽"] = "Concealment"
TR["開口"] = "Opening"
TR["開闊"] = "Open"

# ---- scene codes ----
TR["E1（追逐）"] = "E1 (Chase)"
TR["E2（環境／領域造物）"] = "E2 (Environment / Realm Creation)"
TR["E2（追逐）"] = "E2 (Chase)"
TR["E3（環境）"] = "E3 (Environment)"
TR["E3（領域造物）"] = "E3 (Realm Creation)"
TR["E4（追逐／掛鉤救援）"] = "E4 (Chase / Hook Rescue)"
TR["E4（領域造物）"] = "E4 (Realm Creation)"
TR["E5（追逐）"] = "E5 (Chase)"
TR["E5（追逐／死亡陷阱）"] = "E5 (Chase / Death Trap)"
TR["E5（追逐／首領前）"] = "E5 (Chase / Pre-Boss)"
TR["E6（追加試煉）"] = "E6 (Additional Trial)"
TR["追逐"] = "Chase"
TR["環境"] = "Environment"
TR["領域造物"] = "Realm Creation"
TR["掛鉤救援"] = "Hook Rescue"
TR["死亡陷阱"] = "Death Trap"
TR["首領前"] = "Pre-Boss"
TR["追加試惡"] = "Additional Trial"
TR["追加試煉"] = "Additional Trial"

# ---- SVG labels ----
TR["地圖"] = "Map"
TR["圖例"] = "Legend"
TR["主建物"] = "Main Building"
TR["入口"] = "Entrance"
TR["出口"] = "Exit"
TR["制高點"] = "Vantage Point"
TR["可選"] = "Optional"
TR["地標"] = "Landmark"
TR["寶箱（Chest）"] = "Chest"
TR["建物層"] = "Building Level"
TR["掩體區"] = "Cover Zone"
TR["特殊"] = "Special"
TR["通道"] = "Passage"
TR["開闊區"] = "Open Area"
TR["主區"] = "Main Zone"
TR["主地標"] = "Main Landmark"
TR["主場"] = "Main Arena"
TR["房間"] = "Room"
TR["房間／殘影"] = "Room / Afterimage"
TR["掩體地標"] = "Cover Landmark"
TR["關鍵"] = "Key"
TR["關鍵地標"] = "Key Landmark"
TR["死路"] = "Dead End"
TR["殘影"] = "Afterimage"
TR["無名之心"] = "The Nameless Heart"
TR["營火"] = "Campfire"
TR["虛空"] = "The Void"
TR["通道／刻痕"] = "Passage / Notch"
TR["特殊／刻痕"] = "Special / Notch"
TR["可選／刻痕"] = "Optional / Notch"
TR["地標／刻痕"] = "Landmark / Notch"
TR["制高點／刻痕"] = "Vantage Point / Notch"
TR["危險"] = "Hazard"
TR["遮蔽區"] = "Concealment Zone"
TR["開闊"] = "Open"
TR["第三幕"] = "Act 3"
TR["終局"] = "Endgame"
TR["臍帶（Umbilical）"] = "Umbilical"
TR["不可通行，可傳火（燎原路線）"] = "Impassable; can pass Ember (Conflagration route)"
TR["領域"] = "Realm"
TR["位置每場變動；地窖（）不固定於任一領域"] = "Positions vary per match; the Hatch is not fixed to any realm"
TR["全圖視覺伏筆；玩家首次看圖即注意到紅線（臍帶），才知是什麼"] = "Full-map visual foreshadowing; players notice the red line (Umbilical) on first sight, only then realizing what it is"

# ---- meta.name / titles (exploration + battle) ----
TR["世界地圖（World Map）"] = "World Map"
TR["探索圖·麥克米蘭莊園"] = "Exploration Map · Macmillan Estate"
TR["探索圖·麥克米蘭莊園（MacMillan Estate, R1）"] = "Exploration Map · Macmillan Estate (R1)"
TR["探索圖·廢車場"] = "Exploration Map · Autohaven Wreckers"
TR["探索圖·廢車場（Autohaven Wreckers, R2）"] = "Exploration Map · Autohaven Wreckers (R2)"
TR["探索圖·寒風農場與霧窖"] = "Exploration Map · Coldwind Farm & Fog Cellar"
TR["探索圖·寒風農場（Coldwind Farm, R3） → 霧窖（Fog Cellar）"] = "Exploration Map · Coldwind Farm (R3) → Fog Cellar"
TR["探索圖·克羅特斯精神病院"] = "Exploration Map · Crotus Prenn Asylum"
TR["探索圖·克羅特斯精神病院（Crotus Prenn Asylum, R4）"] = "Exploration Map · Crotus Prenn Asylum (R4)"
TR["探索圖·死水沼澤、虛空與隱室"] = "Exploration Map · Backwater Swamp, The Void & Hidden Workshop"
TR["探索圖·死水沼澤（Backwater Swamp, R5） → 虛空（The Void） → 隱室（Hidden Workshop）"] = "Exploration Map · Backwater Swamp (R5) → The Void → Hidden Workshop"
TR["探索圖·雷利紀念研究所"] = "Exploration Map · Léry's Memorial Institute"
TR["探索圖·雷利紀念研究所（Léry's Memorial Institute, R6）"] = "Exploration Map · Léry's Memorial Institute (R6)"
TR["探索圖·血紅森林與淨罪神殿"] = "Exploration Map · Red Forest & Sin-Cleansing Temple"
TR["探索圖·血紅森林（Red Forest, R7）"] = "Exploration Map · Red Forest (R7)"
TR["探索圖·遺棄骨場、孤塔與無名之心"] = "Exploration Map · Forsaken Boneyard, Lone Tower & The Nameless Heart"
TR["探索圖·遺棄骨場（Forsaken Boneyard, R8） → 孤塔（Lone Tower） → 無名之心（The Nameless Heart）"] = "Exploration Map · Forsaken Boneyard (R8) → Lone Tower → The Nameless Heart"
TR["戰鬥圖·蔽蔭林首次追逐"] = "Battle Map · First Chase in Shelter Woods"
TR["戰鬥圖·玉米田開闊追逐"] = "Battle Map · Open Chase in Cornfield"
TR["戰鬥圖·穗行者玉米田"] = "Battle Map · Stalk-row Walker in Cornfield"
TR["戰鬥圖·屠宰場內近身追逐"] = "Battle Map · Close-quarters Chase in Slaughterhouse"
TR["戰鬥圖·鐵谷隱形突襲"] = "Battle Map · Stealth Ambush in Canyon"
TR["戰鬥圖·車堆坍塌"] = "Battle Map · Car-pile Collapse"
TR["戰鬥圖·閃現追逐"] = "Battle Map · Blink Chase"
TR["戰鬥圖·灰咽病房"] = "Battle Map · Ash Throat Ward"
TR["戰鬥圖·病歷室封閉"] = "Battle Map · Sealed Records Room"
TR["戰鬥圖·巫婆陷阱網"] = "Battle Map · Hag's Trap Net"
TR["戰鬥圖·深水區"] = "Battle Map · Deep Water Zone"
TR["戰鬥圖·無心跳追逐"] = "Battle Map · Heartbeat-less Chase"
TR["戰鬥圖·治療劇場暴露"] = "Battle Map · Exposure in Treatment Theater"
TR["戰鬥圖·鏡像交換"] = "Battle Map · Mirror Swap"
TR["戰鬥圖·獵斧女遠程投擲"] = "Battle Map · Huntress Ranged Throw"
TR["戰鬥圖·神殿內存活"] = "Battle Map · Survival inside Temple"
TR["戰鬥圖·狂徒軍團連續突進"] = "Battle Map · Legion's Continuous Charge"
TR["戰鬥圖·塔頂最終追逐"] = "Battle Map · Final Chase atop Tower"
TR["戰鬥圖·倉庫二樓掛鉤救援"] = "Battle Map · Hook Rescue on Warehouse 2F"
TR["戰鬥圖·孤塔塔頂最終追逐"] = "Battle Map · Final Chase atop Lone Tower"
TR["戰鬥圖·遺棄骨場狂徒軍團突進"] = "Battle Map · Legion's Charge in Forsaken Boneyard"
TR["戰鬥圖·血紅森林獵斧女遠程"] = "Battle Map · Huntress Ranged in Red Forest"
TR["戰鬥圖·泥沼巫婆陷阱網"] = "Battle Map · Hag's Trap Net in Mud"

# ---- comments (header lines) ----
TR["# S1 戰鬥圖 01 · 蔽蔭林首次追逐（E2，GM 必須讓玩家逃掉）"] = "# S1 Battle Map 01 · First Chase in Shelter Woods (E2, GM must let the player escape)"
TR["# S1 戰鬥圖 02 · 倉庫二樓掛鉤救援（E4，教救援）"] = "# S1 Battle Map 02 · Hook Rescue on Warehouse 2F (E4, teaches rescue)"
TR["# S1 探索圖 · 麥克米蘭莊園（MacMillan Estate, R1）"] = "# S1 Exploration Map · Macmillan Estate (MacMillan Estate, R1)"
TR["# S2 戰鬥圖 01 · 鐵谷隱形突襲（E2，無心跳教學）"] = "# S2 Battle Map 01 · Stealth Ambush in Canyon (E2, heartbeat-less tutorial)"
TR["# S2 戰鬥圖 02 · 車堆坍塌（E3，通道封閉）"] = "# S2 Battle Map 02 · Car-pile Collapse (E3, passage sealed)"
TR["# S2 探索圖 · 廢車場（Autohaven Wreckers, R2）"] = "# S2 Exploration Map · Autohaven Wreckers (Autohaven Wreckers, R2)"
TR["# S3 戰鬥圖 01 · 玉米田開闊追逐（E1，鏈鋸屠夫主場）"] = "# S3 Battle Map 01 · Open Chase in Cornfield (E1, Hillbilly's home turf)"
TR["# S3 戰鬥圖 02 · 穗行者玉米田（E4，稻草殘影偽裝）"] = "# S3 Battle Map 02 · Stalk-row Walker in Cornfield (E4, Straw Afterimage disguise)"
TR["# S3 戰鬥圖 03 · 屠宰場內近身追逐（E5，唯一封閉空間）"] = "# S3 Battle Map 03 · Close-quarters Chase in Slaughterhouse (E5, only enclosed space)"
TR["# S3 探索圖 · 寒風農場（Coldwind Farm, R3） → 霧窖（Fog Cellar）"] = "# S3 Exploration Map · Coldwind Farm (Coldwind Farm, R3) → Fog Cellar"
TR["# S4 戰鬥圖 01 · 閃現追逐（E1，護士穿牆）"] = "# S4 Battle Map 01 · Blink Chase (E1, Nurse phases through walls)"
TR["# S4 戰鬥圖 02 · 灰咽病房（E3，病房殘影）"] = "# S4 Battle Map 02 · Ash Throat Ward (E3, Ward Afterimage)"
TR["# S4 戰鬥圖 03 · 病歷室封閉（E5，死亡陷阱）"] = "# S4 Battle Map 03 · Sealed Records Room (E5, death trap)"
TR["# S4 探索圖 · 克羅特斯精神病院（Crotus Prenn Asylum, R4）"] = "# S4 Exploration Map · Crotus Prenn Asylum (Crotus Prenn Asylum, R4)"
TR["# S5 戰鬥圖 01 · 巫婆陷阱網（E1，空間不可信）"] = "# S5 Battle Map 01 · Hag's Trap Net (E1, space untrustworthy)"
TR["# S5 戰鬥圖 02 · 深水區（E2，浮腫者拖慢）"] = "# S5 Battle Map 02 · Deep Water Zone (E2, The Bloated slows you)"
TR["# S5 探索圖 · 死水沼澤（Backwater Swamp, R5） → 虛空（The Void） → 隱室（Hidden Workshop）"] = "# S5 Exploration Map · Backwater Swamp (Backwater Swamp, R5) → The Void → Hidden Workshop"
TR["# S6 戰鬥圖 01 · 無心跳追逐（E1，緘默者）"] = "# S6 Battle Map 01 · Heartbeat-less Chase (E1, The Silent One)"
TR["# S6 戰鬥圖 02 · 治療劇場暴露（E5，無掩體）"] = "# S6 Battle Map 02 · Exposure in Treatment Theater (E5, no cover)"
TR["# S6 戰鬥圖 03 · 鏡像交換（E3，地圖記憶失效）"] = "# S6 Battle Map 03 · Mirror Swap (E3, map memory fails)"
TR["# S6 探索圖 · 雷利紀念研究所（Léry's Memorial Institute, R6）"] = "# S6 Exploration Map · Léry's Memorial Institute (Léry's Memorial Institute, R6)"
TR["# S7 戰鬥圖 01 · 獵斧女遠程投擲（E1，距離不再安全）"] = "# S7 Battle Map 01 · Huntress Ranged Throw (E1, distance no longer safe)"
TR["# S7 戰鬥圖 02 · 神殿內存活（E6，追加試煉）"] = "# S7 Battle Map 02 · Survival inside Temple (E6, additional trial)"
TR["# S7 探索圖 · 血紅森林（Red Forest, R7）"] = "# S7 Exploration Map · Red Forest (Red Forest, R7)"
TR["# S8 戰鬥圖 01 · 狂徒軍團連續突進（E2，深傷）"] = "# S8 Battle Map 01 · Legion's Continuous Charge (E2, Deep Wound)"
TR["# S8 戰鬥圖 02 · 塔頂最終追逐（E5，純速度）"] = "# S8 Battle Map 02 · Final Chase atop Tower (E5, pure speed)"
TR["# S8 探索圖 · 遺棄骨場（Forsaken Boneyard, R8） → 孤塔（Lone Tower） → 無名之心（The Nameless Heart）"] = "# S8 Exploration Map · Forsaken Boneyard (Forsaken Boneyard, R8) → Lone Tower → The Nameless Heart"
TR["# 世界地圖（領域關係圖，拓撲關係，非地理圖）"] = "# World Map (Realm relation map; topological, not geographic)"
TR["# 座標範圍 0-1000，y 上小下大。共 20 節點、32 連線。"] = "# Coordinate range 0-1000, smaller y at top. 20 nodes, 32 connections."
TR["# 註：指令預期 33 連線，但 40 檔 §3-3 實際錄為 32 條，此處忠實轉錄 32 條。"] = "# Note: the directive expected 33 connections, but file 40 §3-3 actually records 32; faithfully transcribed as 32 here."

# ---- notes (meta.note / node.note) ----
TR["教學追逐，無板子壓力、無造物；必須讓玩家逃掉。座標為格位（格公尺），原點左上。"] = "Tutorial chase, no pallet pressure, no creations; the player must be allowed to escape. Coordinates in grid cells (grid metres), origin top-left."
TR["室內二樓，含窗戶通往煤塔頂；教學：掛鉤（）與救援。座標格位（格公尺），原點左上。"] = "Interior 2F, with a window to the Coal Tower top; tutorial: hooks and rescue. Coordinates in grid cells (grid metres), origin top-left."
TR["戰鬥圖·倉庫二樓掛鉤救援（，教救援）"] = "Battle Map · Hook Rescue on Warehouse 2F (, teaches rescue)"
TR["戰鬥圖·塔頂最終追逐（，純速度）"] = "Battle Map · Final Chase atop Tower (, pure speed)"
TR["戰鬥圖·孤塔塔頂最終追逐"] = "Battle Map · Final Chase atop Lone Tower"
TR["戰鬥圖·屠宰場內近身追逐（，唯一封閉空間）"] = "Battle Map · Close-quarters Chase in Slaughterhouse (, only enclosed space)"
TR["戰鬥圖·巫婆陷阱網（，空間不可信）"] = "Battle Map · Hag's Trap Net (, space untrustworthy)"
TR["戰鬥圖·治療劇場暴露（，無掩體）"] = "Battle Map · Exposure in Treatment Theater (, no cover)"
TR["戰鬥圖·泥沼巫婆陷阱網"] = "Battle Map · Hag's Trap Net in Mud"
TR["戰鬥圖·深水區（，浮腫者拖慢）"] = "Battle Map · Deep Water Zone (, The Bloated slows you)"
TR["戰鬥圖·灰咽病房（，病房殘影）"] = "Battle Map · Ash Throat Ward (, Ward Afterimage)"
TR["戰鬥圖·無心跳追逐（，緘默者）"] = "Battle Map · Heartbeat-less Chase (, The Silent One)"
TR["戰鬥圖·狂徒軍團連續突進（，深傷）"] = "Battle Map · Legion's Continuous Charge (, Deep Wound)"
TR["戰鬥圖·獵斧女遠程投擲（，距離不再安全）"] = "Battle Map · Huntress Ranged Throw (, distance no longer safe)"
TR["戰鬥圖·玉米田開闊追逐（，鏈鋸屠夫主場）"] = "Battle Map · Open Chase in Cornfield (, Hillbilly's home turf)"
TR["戰鬥圖·病歷室封閉（，死亡陷阱）"] = "Battle Map · Sealed Records Room (, death trap)"
TR["戰鬥圖·神殿內存活（，追加試煉）"] = "Battle Map · Survival inside Temple (, additional trial)"
TR["戰鬥圖·穗行者玉米田（，稻草殘影偽裝）"] = "Battle Map · Stalk-row Walker in Cornfield (, Straw Afterimage disguise)"
TR["戰鬥圖·蔽蔭林首次追逐（，必須讓玩家逃掉）"] = "Battle Map · First Chase in Shelter Woods (, player must be allowed to escape)"
TR["戰鬥圖·血紅森林獵斧女遠程"] = "Battle Map · Huntress Ranged in Red Forest"
TR["戰鬥圖·車堆坍塌（，通道封閉）"] = "Battle Map · Car-pile Collapse (, passage sealed)"
TR["戰鬥圖·遺棄骨場狂徒軍團突進"] = "Battle Map · Legion's Charge in Forsaken Boneyard"
TR["戰鬥圖·鏡像交換（，地圖記憶失效）"] = "Battle Map · Mirror Swap (, map memory fails)"
TR["戰鬥圖·鐵谷隱形突襲（，無心跳教學）"] = "Battle Map · Stealth Ambush in Canyon (, heartbeat-less tutorial)"
TR["戰鬥圖·閃現追逐（，護士穿牆）"] = "Battle Map · Blink Chase (, Nurse phases through walls)"
TR["開闊地是鏈鋸屠夫（）主場，全戰役到目前最痛的一場；只有面板子（），靠玉米田遮蔽玩心理戰。座標格位（格公尺），原點左上。"] = "Open ground is the Hillbilly's home turf, the most painful fight so far this campaign; only flat pallets, using Cornfield concealment for mind games. Coordinates in grid cells (grid metres), origin top-left."
TR["泥沼巫婆（）泥符（）佈局＋幻影瞬移（），可在淺水佈泥像陷阱（雷區）；空間不可信。座標格位（格公尺），原點左上。"] = "The Hag lays Mud Glyphs and Phantasm Teleport, and can place Mud Glyph Traps (minefield) in shallow water; space is untrustworthy. Coordinates in grid cells (grid metres), origin top-left."
TR["巫婆在深水上方俯瞰，玩家須涉水通過"] = "The Hag overlooks from above the deep water; players must wade across."
TR["三段深水區，每段敏捷（）或意志（）檢定（困困）；水中浮腫者＝泥手（-）抓住涉水者拖慢移動。座標格位（格公尺），原點左上。"] = "Three segments of deep water, each an Agility or Will check (Difficult); The Bloated in the water = Mud Hands (-) grabs waders and slows movement. Coordinates in grid cells (grid metres), origin top-left."
TR["全戰役唯一封閉空間，近身追逐極致命。座標格位（格公尺），原點左上。"] = "The only fully enclosed space in the campaign; close-quarters chase is extremely lethal. Coordinates in grid cells (grid metres), origin top-left."
TR["唯一單出口戰鬥地圖；護士在玩家進入後才出現在門口，不追進來，只是站著，緩慢敲桌。座標格位（格公尺），原點左上。"] = "The only single-exit battle map; the Nurse appears at the door only after the player enters, does not chase in, just stands and slowly taps the table. Coordinates in grid cells (grid metres), origin top-left."
TR["護士在門口（），不主動追入，緩慢敲桌"] = "The Nurse is at the door, does not actively chase in, slowly taps the table."
TR["幽咽護士（）閃現（）可穿越樓層與牆體；全封閉、視線極短。座標格位（格公尺），原點左上。"] = "The Wraith's Blink can cross floors and walls; fully enclosed, very short line of sight. Coordinates in grid cells (grid metres), origin top-left."
TR["幽靈（）無恐怖半徑（），玩家聽不到心跳；靠聽覺線索判斷方位。座標格位（格公尺），原點左上。"] = "The Wraith has no Terror Radius; players cannot hear a heartbeat, relying on audio cues to judge direction. Coordinates in grid cells (grid metres), origin top-left."
TR["灰咽＝病房殘影（-），焦炭狀造物發出病患哀號干擾聽覺辨位。座標格位（格公尺），原點左上。"] = "Ash Throat = Ward Afterimage (-), a charred creation emitting patients' wails that disrupt audio-based positioning. Coordinates in grid cells (grid metres), origin top-left."
TR["緘默者（）無恐怖半徑（）（無心跳，最大恐怖來源）；完全不敲桌。座標格位（格公尺），原點左上。"] = "The Silent One has no Terror Radius (no heartbeat, the greatest source of dread); never taps the table. Coordinates in grid cells (grid metres), origin top-left."
TR["治療劇場無掩體，極高壓；緘默者（）暴露突襲。座標格位（格公尺），原點左上。"] = "The Treatment Theater has no cover and is extremely high-pressure; The Silent One strikes from exposure. Coordinates in grid cells (grid metres), origin top-left."
TR["玩家進入範圍或受到攻擊時，格位變為不可通行（封閉通道）"] = "When the player enters the area or is attacked, the cell becomes impassable (sealed passage)."
TR["觸發後通道封閉，敏捷（）閃避。座標格位（格公尺），原點左上。"] = "After triggering, the passage seals; Agility to dodge. Coordinates in grid cells (grid metres), origin top-left."
TR["鏡像交換發生時，兩翼對稱節點互換、不變，地圖記憶失效一次。座標格位（格公尺），原點左上；左右完全對稱。"] = "When Mirror Swap occurs, the symmetric nodes of the two wings swap, unchanged, and map memory fails once. Coordinates in grid cells (grid metres), origin top-left; fully left-right symmetric."
TR["鏡像對稱設計與節點結構完全相同；「鏡像交換」發生時，兩翼互換、不變。"] = "Mirror-symmetric design with identical node structure; when 'Mirror Swap' occurs, the two wings swap, unchanged."
TR["獵斧女（）手斧（）遠程投擲，距離帶（）以內目標皆可攻擊，巨樹是唯一防護；開闊林地無安全距離。座標格位（格公尺），原點左上。"] = "The Huntress throws Hand Axes at range; any target within the Distance Band can be hit, the Giant Tree is the only cover; open woods have no safe distance. Coordinates in grid cells (grid metres), origin top-left."
TR["若營火餘燼（）門檻，須在神殿內存活指定輪數後帶餘燼離開（傳奇難度）。座標格位（格公尺），原點左上。"] = "If the Campfire Ember threshold is met, survive a set number of rounds inside the temple, then leave with the ember (Legendary difficulty). Coordinates in grid cells (grid metres), origin top-left."
TR["獵斧女（）或緘默者（）依選擇；存活輪數見人數表"] = "Huntress or The Silent One, by choice; survival rounds per the player-count table."
TR["狂徒軍團（）狂暴（）連續突進，擊中施加深傷（），非移動時持續流失「停下來就是死」。座標格位（格公尺），原點左上。"] = "Legion's Frenzy drives continuous charges; hits inflict Deep Wound, and standing still steadily drains ('stop and you die'). Coordinates in grid cells (grid metres), origin top-left."
TR["塔頂最終追逐，純速度／行動點（）；通過天穹裂口（）進入無名之心。座標格位（格公尺），原點左上。"] = "Final chase atop the tower, pure speed / Action Points; pass through the Sky-roof Rift to enter The Nameless Heart. Coordinates in grid cells (grid metres), origin top-left."
TR["位置每場變動；地窖（Hatch）不固定於任一領域"] = "Positions vary per match; the Hatch is not fixed to any realm."
TR["全圖視覺伏筆；玩家首次看圖即注意到紅線（臍帶），才知是什麼"] = "Full-map visual foreshadowing; players notice the red line (Umbilical) on first sight, only then realizing what it is."
TR["實體的領域以非歐幾里得拼接，距離無意義，連線關係才有意義。營火正中、八領域環內環、虛空在下緣、孤塔左上、無名之心正上方最遠。"] = "The Entity's realms are stitched non-Euclidiean; distance is meaningless, only connection relations matter. The Campfire at center, eight realms in the inner ring, The Void at the lower edge, Lone Tower top-left, The Nameless Heart farthest directly above."
TR["霧窖節點與地表座標重疊是刻意的霧窖在空間上就在農場底下，是同一位置的另一層。"] = "The Fog Cellar node deliberately overlaps surface coordinates; spatially it sits beneath the farm, another layer of the same location."

# ---- conditions (world map edges) ----
TR["僅在供品（Offering）燃燒時開啟"] = "Opens only when an Offering is burning"
TR["實體指派"] = "Entity-assigned"
TR["S3 完成後永久"] = "Permanent after S3"
TR["S4 完成後永久"] = "Permanent after S4"
TR["S5 完成後永久"] = "Permanent after S5"
TR["S7 完成後"] = "After S7"
TR["S5 期間單向向下；完成後雙向"] = "One-way down during S5; two-way after"
TR["虛空內自由"] = "Free within the Void"
TR["單向（虛空→隱室），需在虛空中重新產生情緒"] = "One-way (Void→Hidden Workshop); must regenerate emotion in the Void"
TR["需持有餘燼（Ember）方能真正向上"] = "Requires holding an Ember to truly ascend"
TR["僅 S8 第三幕"] = "Act 3 of S8 only"
TR["不可通行，但可傳火（S8 燎原路線）"] = "Impassable, but Ember can be passed (S8 Conflagration route)"
TR["不可通行；僅供光環／視覺提示"] = "Impassable; aura / visual cue only"
TR["單向（現實→領域）"] = "One-way (Reality→Realm)"
TR["僅在人數條件達成時開啟"] = "Opens only when the player-count condition is met"

# ---- 說明 / 中文名 / 底色 (world map regions) ----
TR["營火與其正下方的結構"] = "The Campfire and the structure directly beneath it"
TR["八個試煉領域"] = "The eight Trial realms"
TR["實體控制不完全的異常空間"] = "Anomalous space under incomplete Entity control"
TR["棄置地"] = "Abandoned place"
TR["滲點所在，不屬於實體領域"] = "Where the Seeps are; not part of the Entity's realms"
TR["核心層"] = "Core Layer"
TR["內環·領域帶"] = "Inner Ring · Realm Belt"
TR["外緣·裂界帶"] = "Outer Edge · Rift Belt"
TR["外緣·虛空"] = "Outer Edge · The Void"
TR["現實側"] = "Mortal Side"
TR["暖橙"] = "Warm Orange"
TR["冷灰"] = "Cool Gray"
TR["靛藍"] = "Indigo"
TR["近黑紫"] = "Near-black Purple"
TR["濁綠"] = "Murky Green"

# ---- world-map edge names ----
TR["霧路·鏽鐵"] = "Mist Road · Rust Iron"
TR["霧路·鐵谷"] = "Mist Road · Canyon"
TR["霧路·穗浪"] = "Mist Road · Grain Wave"
TR["霧路·焦灰"] = "Mist Road · Scorched Ash"
TR["霧路·濁水"] = "Mist Road · Turbid Water"
TR["霧路·白瓷"] = "Mist Road · White Porcelain"
TR["霧路·紅頂"] = "Mist Road · Red Roof"
TR["霧路·風沙"] = "Mist Road · Wind Sand"
TR["鏽縫"] = "Rust Rift"
TR["穀鐵縫"] = "Grain-iron Rift"
TR["病田縫"] = "Sick-field Rift"
TR["灰水縫"] = "Ash-water Rift"
TR["排污縫"] = "Drainage Rift"
TR["根管縫"] = "Root-canal Rift"
TR["落葉縫"] = "Fallen-leaves Rift"
TR["塵鏽縫"] = "Dust-rust Rift"
TR["樹下的根道"] = "Root Passage beneath the Tree"
TR["病歷長廊"] = "Records Long Corridor"
TR["沉沒階"] = "Sunken Stair"
TR["殘影漂"] = "Afterimage Drift"
TR["棄物漂"] = "Midden Drift"
TR["棄物迴流"] = "Midden Backflow"
TR["排水暗渠"] = "Drainage Channel"
TR["拾遺者的隱門"] = "Scavenger's Hidden Door"
TR["無盡階"] = "Endless Stair"
TR["天穹裂口"] = "Sky-roof Rift"
TR["燼下"] = "Ember-below"
TR["臍帶"] = "Umbilical"
TR["最初的根"] = "First Root"
TR["滲入"] = "Seep In"
TR["地窖（Hatch）"] = "Hatch"
TR["迷霧通道"] = "Mist Corridor"

# ---- misc node/edge names that are idiomatic ----
TR["蔽蔭林"] = "Shelter Woods"
TR["那棵粗樹"] = "The Big Tree"
TR["呻吟倉庫"] = "Groaning Warehouse"
TR["悲鳴鐵工廠"] = "Wailing Ironworks"
TR["煤塔"] = "Coal Tower"
TR["煤塔頂層"] = "Coal Tower Top Floor"
TR["熔爐排"] = "Furnace Row"
TR["窒息坑"] = "Suffocation Pit"
TR["坑緣棧道"] = "Pit-edge Catwalk"
TR["鏽箱 A"] = "Rusty Chest A"
TR["鏽箱 B"] = "Rusty Chest B"
TR["破工寮"] = "Broken Shack"
TR["更衣間"] = "Locker Room"
TR["碼頭"] = "Dock"
TR["蒼白玫瑰號"] = "Pale Rose"
TR["母之居"] = "Mother's Dwelling"
TR["母之居火塘"] = "Mother's Dwelling Hearth"
TR["獻祭之樹"] = "Tree of Sacrifice"
TR["淨罪神殿"] = "Sin-Cleansing Temple"
TR["持鏡人所在"] = "Where the Mirror-Bearer Is"
TR["持鏡人"] = "Mirror-Bearer"
TR["餘燼龕"] = "Ember Niche"
TR["血祭壇"] = "Blood Altar"
TR["無名墓"] = "Nameless Grave"
TR["獵人小屋"] = "Hunter's Cabin"
TR["紅葉海"] = "Red Leaf Sea"
TR["立石圈"] = "Standing Stone Circle"
TR["老井"] = "Old Well"
TR["雞舍"] = "Chicken Coop"
TR["農具棚"] = "Tool Shed"
TR["車庫"] = "Garage"
TR["穀倉筒"] = "Silo"
TR["收割機"] = "Harvester"
TR["吊車"] = "Crane"
TR["油槽"] = "Oil Tank"
TR["校車"] = "School Bus"
TR["油桶"] = "Oil Drum"
TR["車堆"] = "Car Pile"
TR["廢車堆"] = "Wreck Pile"
TR["廢車牆"] = "Wreck Wall"
TR["車廂"] = "Railcar"
TR["翻覆貨卡"] = "Overturned Truck"
TR["貨架"] = "Shelf"
TR["病牀"] = "Hospital Bed"
TR["手術台"] = "Operating Table"
TR["病房隔牆"] = "Ward Partition"
TR["病房隔簾"] = "Ward Curtain"
TR["病歷架"] = "Records Rack"
TR["石像圈"] = "Stone Statue Circle"
TR["石柱"] = "Stone Pillar"
TR["觀察窗"] = "Observation Window"
TR["觀眾席"] = "Auditorium"
TR["講壇"] = "Pulpit"
TR["治療劇場"] = "Treatment Theater"
TR["電療室"] = "Electrotherapy Room"
TR["藥品櫃"] = "Medicine Cabinet"
TR["藥櫃"] = "Medicine Cabinet"
TR["神父的箱子"] = "Priest's Box"
TR["禮拜堂"] = "Chapel"
TR["停屍間"] = "Morgue"
TR["鐘樓"] = "Bell Tower"
TR["塔基"] = "Tower Base"
TR["塔頂"] = "Tower Top"
TR["塔緣矮牆"] = "Tower-edge Low Wall"
TR["塔門"] = "Tower Door"
TR["烏鴉巢"] = "Crow's Nest"
TR["骨堆"] = "Bone Pile"
TR["風蝕洞"] = "Wind-eroded Cave"
TR["沙丘"] = "Sand Dune"
TR["沙下寶箱"] = "Sand-buried Chest"
TR["雕座"] = "Statue Pedestal"
TR["雕座寶箱"] = "Statue-pedestal Chest"
TR["石下寶箱"] = "Under-rock Chest"
TR["樹洞寶箱"] = "Hollow-tree Chest"
TR["船艙寶箱"] = "Ship-cabin Chest"
TR["棚下寶箱"] = "Under-shed Chest"
TR["車廂寶箱"] = "Railcar Chest"
TR["工具箱堆"] = "Toolbox Pile"
TR["法恩的裝置"] = "Fane's Device"
TR["泥像陷阱"] = "Mud Glyph Trap"
TR["浮腫者"] = "The Bloated"
TR["灰咽"] = "Ash Throat"
TR["穗行者"] = "The Stalk-row Walker"
TR["巨樹"] = "Giant Tree"
TR["蘆葦"] = "Reed"
TR["深水區"] = "Deep Water Zone"
TR["淺水"] = "Shallow Water"
TR["涉水淺灘"] = "Wading Shoal"
TR["沉沒神龕"] = "Sunken Shrine"
TR["沉沒階"] = "Sunken Stair"
TR["暗渠"] = "Drainage Channel"
TR["根道"] = "Root Passage"
TR["隱室"] = "Hidden Workshop"
TR["霧窖"] = "Fog Cellar"
TR["滲點"] = "Seep"
TR["滲點·威克斯鎮"] = "Seep · Wick's Town"
TR["滲點·未名"] = "Seep · Unnamed"
TR["餘燼脈"] = "Ember Vein"
TR["臍帶"] = "Umbilical"
TR["裂隙"] = "Rift"
TR["天穹裂口"] = "Sky-roof Rift"
TR["肉鉤架"] = "Meat-hook Rack"
TR["屠宰台"] = "Slaughter Table"
TR["屠宰場"] = "Slaughterhouse"
TR["不穩車堆"] = "Unstable Car Pile"
TR["車堆頂"] = "Car-pile Top"
TR["鐵谷崖壁"] = "Canyon Cliff"
TR["天井"] = "Atrium"
TR["開口原"] = "Opening Plain"
TR["無方向"] = "No Direction"
TR["錯階"] = "Misaligned Stairs"
TR["螺旋梯"] = "Spiral Stair"
TR["無盡階"] = "Endless Stair"
TR["石廊"] = "Stone Corridor"
TR["石廊深處"] = "Stone Corridor Depths"
TR["石廊鏡廊"] = "Stone Corridor Mirror Gallery"
TR["石廊龕側"] = "Stone Corridor Niche Side"
TR["石門側室門"] = "Stone Door Side-room Door"
TR["翼房間"] = "Wing Room"
TR["翼隔牆"] = "Wing Partition"
TR["走廊隔牆"] = "Corridor Partition"
TR["病房隔牆"] = "Ward Partition"
TR["牆體"] = "Wall"
TR["外牆裂縫"] = "Outer Wall Crack"
TR["破洞地板"] = "Broken Floor"
TR["破口"] = "Breach"
TR["暗門"] = "Secret Door"
TR["密道"] = "Secret Passage"
TR["地板格柵"] = "Floor Grate"
TR["排水暗渠口"] = "Drainage Outlet"
TR["單面鏡窗"] = "One-way Mirror Window"
TR["觀眾席階梯"] = "Auditorium Stairs"
TR["鐘樓梯"] = "Bell Tower Stairs"
TR["病房梯"] = "Ward Stairs"
TR["船梯"] = "Ship Ladder"
TR["木梯"] = "Wooden Ladder"
TR["鏽梯"] = "Rusty Ladder"
TR["觀眾席梯"] = "Auditorium Stairs"
TR["塔梯"] = "Tower Ladder"
TR["窗戶"] = "Window"
TR["跳下"] = "Drop"
TR["懸垂根"] = "Hanging Root"
TR["根系"] = "Root System"
TR["最初的根"] = "First Root"
TR["同源臍帶"] = "Shared Umbilical"
TR["起始霧口"] = "Starting Fog Mouth"
TR["那個洞"] = "That Hole"
TR["你的那一條霧窖"] = "Your Fog Cellar"
TR["他的地方"] = "His Place"
TR["我們的"] = "Our"
TR["他在的地方"] = "Where He Is"
TR["根系·近層霧窖"] = "Root System · Near-layer Fog Cellar"
TR["根系·中層霧窖"] = "Root System · Mid-layer Fog Cellar"
TR["根系·深層霧窖"] = "Root System · Deep-layer Fog Cellar"
TR["霧窖·入口"] = "Fog Cellar · Entrance"
TR["隱室·隱室"] = "Hidden Workshop"
TR["無名所在"] = "The Nameless Place"
TR["裂隙·天穹裂口"] = "Rift · Sky-roof Rift"
TR["開口·天井底"] = "Opening · Atrium Bottom"
TR["無名之心·終局"] = "The Nameless Heart · Endgame"
TR["無名之心·無名之心"] = "The Nameless Heart"
TR["餘燼脈·無名之心"] = "Ember Vein · The Nameless Heart"
TR["臍帶·不可通行，可傳火"] = "Umbilical · Impassable, can pass Ember"
TR["虛空·棄物淵"] = "The Void · Midden Abyss"
TR["虛空·殘影原"] = "The Void · Afterimage Plain"
TR["虛空·沉沒帶"] = "The Void · Sunken Belt"
TR["虛空·漂移更深處"] = "The Void · Drift Deeper"
TR["虛空·棄物漂"] = "The Void · Midden Drift"
TR["虛空·殘影漂"] = "The Void · Afterimage Drift"

# ---------------------------------------------------------------------------
# MORPH: morpheme decomposition for creative names not in TR.
# Applied longest-first within a value. Trailing spaces aid concatenation;
# the final result is rstrip'd and double spaces collapsed.
# ---------------------------------------------------------------------------
MORPH = {}
# macro words
MORPH["探索圖"] = "Exploration Map"
MORPH["戰鬥圖"] = "Battle Map"
MORPH["霧路"] = "Mist Road"
MORPH["霧縫"] = "Mist Rift"
# directions
MORPH["東北"] = "Northeast "
MORPH["西北"] = "Northwest "
MORPH["東南"] = "Southeast "
MORPH["西南"] = "Southwest "
MORPH["北"] = "North "
MORPH["南"] = "South "
MORPH["東"] = "East "
MORPH["西"] = "West "
# suffixes / parts (no leading spaces; some trailing spaces)
MORPH["逃生門"] = "Exit Gate"
MORPH["起始霧口"] = "Starting Fog Mouth"
MORPH["木棧道"] = "Wooden Pier Path"
MORPH["木棧"] = "Wooden Pier"
MORPH["沙地"] = "Sand "
MORPH["落葉地"] = "Fallen Leaves "
MORPH["深林"] = "Deep Woods"
MORPH["玉米田"] = "Cornfield"
MORPH["鐵谷"] = "Canyon"
MORPH["霧縫"] = "Mist Rift"
MORPH["虛空"] = "The Void"
MORPH["根系"] = "Root System"
MORPH["神殿"] = "Temple"
MORPH["翼"] = "Wing"
MORPH["室內"] = "Interior "
MORPH["開闊"] = "Open "
MORPH["樓梯"] = "Stairs"
MORPH["窗戶"] = "Window"
MORPH["攀爬"] = "Climb"
MORPH["窄門"] = "Side Door"
MORPH["窄道"] = "Narrow Path"
MORPH["林道"] = "Woods Path"
MORPH["主路"] = "Main Road"
MORPH["樹下"] = "Under the Tree"
MORPH["南坡"] = "South Slope"
MORPH["側門"] = "Side Door"
MORPH["鏽梯"] = "Rusty Ladder"
MORPH["廠間道"] = "Between-works Path"
MORPH["煤渣路"] = "Cinder Road"
MORPH["堆料區"] = "Material Pile Area"
MORPH["二樓破窗"] = "2F Broken Window"
MORPH["爐廊"] = "Furnace Hall"
MORPH["運煤道"] = "Coal-haul Path"
MORPH["廢料道"] = "Scrap Path"
MORPH["工具間"] = "Tool Room"
MORPH["塔梯"] = "Tower Ladder"
MORPH["高架棧道"] = "Elevated Catwalk"
MORPH["坑壁"] = "Pit Wall"
MORPH["北出口道"] = "North Exit Path"
MORPH["農具道"] = "Tool-shed Path"
MORPH["雞舍徑"] = "Chicken-coop Path"
MORPH["農道"] = "Farm Path"
MORPH["田埂"] = "Field Ridge"
MORPH["宅前道"] = "Front-of-house Path"
MORPH["屠宰道"] = "Slaughter Path"
MORPH["場院"] = "Yard"
MORPH["場邊道"] = "Yard-side Path"
MORPH["東北道"] = "Northeast Path"
MORPH["東南道"] = "Southeast Path"
MORPH["西北道"] = "Northwest Path"
MORPH["谷口"] = "Valley Mouth"
MORPH["車列間"] = "Between Car Rows"
MORPH["車庫道"] = "Garage Path"
MORPH["零件堆"] = "Parts Pile"
MORPH["進場道"] = "Entry Path"
MORPH["北場道"] = "North Yard Path"
MORPH["北向道"] = "Northbound Path"
MORPH["吊車基座"] = "Crane Base"
MORPH["東田埂"] = "East Field Ridge"
MORPH["西田埂"] = "West Field Ridge"
MORPH["穀道"] = "Grain Path"
MORPH["側道"] = "Side Path"
MORPH["北道"] = "North Path"
MORPH["中央道"] = "Central Path"
MORPH["木棧登船板"] = "Wooden Pier Gangplank"
MORPH["木棧東南"] = "Wooden Pier Southeast"
MORPH["木棧東"] = "Wooden Pier East"
MORPH["木棧西"] = "Wooden Pier West"
MORPH["木棧西北"] = "Wooden Pier Northwest"
MORPH["木棧棚下"] = "Wooden Pier Under-shed"
MORPH["木棧籠道"] = "Wooden Pier Cage Path"
MORPH["木棧食品間"] = "Wooden Pier Pantry"
MORPH["木棧籠後水路"] = "Wooden Pier Cage-back Waterway"
MORPH["涉水淺灘"] = "Wading Shoal"
MORPH["涉水籠後水路"] = "Wading Cage-back Waterway"
MORPH["深水第一段"] = "Deep Water Segment 1"
MORPH["深水第二段"] = "Deep Water Segment 2"
MORPH["深水第三段"] = "Deep Water Segment 3"
MORPH["東木棧道"] = "East Wooden Pier Path"
MORPH["西木棧道"] = "West Wooden Pier Path"
MORPH["沙地內圈道"] = "Sand Inner-ring Path"
MORPH["沙地北弧道"] = "Sand North-arc Path"
MORPH["沙地南道"] = "Sand South Path"
MORPH["沙地東丘道"] = "Sand East-hill Path"
MORPH["沙地東出口道"] = "Sand East-exit Path"
MORPH["沙地東雕道"] = "Sand East-statue Path"
MORPH["沙地沙坑"] = "Sand Pit"
MORPH["沙地石像道"] = "Sand Statue Path"
MORPH["沙地裝置道"] = "Sand Device Path"
MORPH["沙地西丘道"] = "Sand West-hill Path"
MORPH["沙地西出口道"] = "Sand West-exit Path"
MORPH["沙地西雕道"] = "Sand West-statue Path"
MORPH["沙地雕座下"] = "Sand Beneath Pedestal"
MORPH["沙地風蝕徑"] = "Sand Wind-eroded Trail"
MORPH["沙地骨堆徑"] = "Sand Bone-pile Trail"
MORPH["落葉地北徑"] = "Fallen Leaves North Trail"
MORPH["落葉地屋前徑"] = "Fallen Leaves Front-of-house Trail"
MORPH["落葉地東南徑"] = "Fallen Leaves Southeast Trail"
MORPH["落葉地東林徑"] = "Fallen Leaves East-woods Trail"
MORPH["落葉地林徑"] = "Fallen Leaves Woods Trail"
MORPH["落葉地樹洞"] = "Fallen Leaves Hollow Tree"
MORPH["落葉地獵徑"] = "Fallen Leaves Hunt Trail"
MORPH["落葉地石下"] = "Fallen Leaves Under-rock"
MORPH["落葉地石徑"] = "Fallen Leaves Stone Trail"
MORPH["落葉地石環外"] = "Fallen Leaves Outside Stone Ring"
MORPH["落葉地神殿道"] = "Fallen Leaves Temple Path"
MORPH["落葉地祭道"] = "Fallen Leaves Ritual Path"
MORPH["落葉地舊墳道"] = "Fallen Leaves Old-grave Path"
MORPH["落葉地葉緣"] = "Fallen Leaves Leaf Edge"
MORPH["落葉地西南徑"] = "Fallen Leaves Southwest Trail"
MORPH["落葉地西林徑"] = "Fallen Leaves West-woods Trail"
MORPH["落葉地舊墳道"] = "Fallen Leaves Old-grave Path"
MORPH["落葉空地"] = "Fallen Leaves Clearing"
MORPH["深林·東"] = "Deep Woods · East"
MORPH["深林·西"] = "Deep Woods · West"
MORPH["玉米田·南田區"] = "Cornfield · South Fields"
MORPH["玉米田·東田區"] = "Cornfield · East Fields"
MORPH["玉米田·西田區"] = "Cornfield · West Fields"
MORPH["鐵谷·中段"] = "Canyon · Mid Section"
MORPH["鐵谷·北段"] = "Canyon · North Section"
MORPH["鐵谷·南段"] = "Canyon · South Section"
MORPH["神殿一層·柱廳"] = "Temple 1F · Pillar Hall"
MORPH["神殿一層·側室"] = "Temple 1F · Side Chamber"
MORPH["神殿二層·錯階"] = "Temple 2F · Misaligned Stairs"
MORPH["神殿二層·鏡廊"] = "Temple 2F · Mirror Gallery"
MORPH["一層·側室神殿一層"] = "1F · Side Chamber (Temple 1F)"
MORPH["二層·錯階神殿二層"] = "2F · Misaligned Stairs (Temple 2F)"
MORPH["二層·鏡廊神殿二層"] = "2F · Mirror Gallery (Temple 2F)"
MORPH["翼·保存室"] = "Wing · Preservation Room"
MORPH["翼·第一長廊"] = "Wing · First Long Corridor"
MORPH["翼·第二長廊"] = "Wing · Second Long Corridor"
MORPH["翼·藥櫃"] = "Wing · Medicine Cabinet"
MORPH["翼·觀察室"] = "Wing · Observation Room"
MORPH["主任辦公室翼"] = "Head Doctor's Office Wing"
MORPH["廢棄病房翼"] = "Abandoned Ward Wing"
MORPH["北拱門"] = "North Arch"
MORPH["南拱門"] = "South Arch"
MORPH["北長廊"] = "North Long Corridor"
MORPH["東長廊"] = "East Long Corridor"
MORPH["北逃生門"] = "North Exit Gate"
MORPH["南逃生門"] = "South Exit Gate"
MORPH["東逃生門"] = "East Exit Gate"
MORPH["西逃生門"] = "West Exit Gate"
MORPH["東北逃生門"] = "Northeast Exit Gate"
MORPH["西北逃生門"] = "Northwest Exit Gate"
MORPH["東南逃生門"] = "Southeast Exit Gate"
MORPH["西南逃生門"] = "Southwest Exit Gate"
MORPH["車堆頂"] = "Car-pile Top"
MORPH["吊車鐵谷"] = "Crane (Canyon)"
MORPH["油槽"] = "Oil Tank"
MORPH["校車"] = "School Bus"
MORPH["油桶"] = "Oil Drum"
MORPH["車庫"] = "Garage"
MORPH["鐵櫃區"] = "Steel-locker Zone"
MORPH["加油站遺址"] = "Gas Station Ruins"
MORPH["場長辦公室"] = "Yard Manager's Office"
MORPH["死路·油桶區"] = "Dead End · Oil-drum Zone"
MORPH["死路·車牆鐵谷"] = "Dead End · Car-wall (Canyon)"
MORPH["翻覆貨卡"] = "Overturned Truck"
MORPH["穿越貨卡"] = "Cross the Truck Bed"
MORPH["窄道油桶巷"] = "Narrow Path · Oil-drum Alley"
MORPH["窄道谷底"] = "Narrow Path · Valley Bottom"
MORPH["窄道車廂縫"] = "Narrow Path · Railcar Gap"
MORPH["窄道車牆巷"] = "Narrow Path · Car-wall Alley"
MORPH["鐵櫃間"] = "Steel-locker Room"
MORPH["吊車基座"] = "Crane Base"
MORPH["車列間"] = "Between Car Rows"
MORPH["塔基"] = "Tower Base"
MORPH["塔頂"] = "Tower Top"
MORPH["石下寶箱"] = "Under-rock Chest"
MORPH["樹洞寶箱"] = "Hollow-tree Chest"
MORPH["船艙寶箱"] = "Ship-cabin Chest"
MORPH["棚下寶箱"] = "Under-shed Chest"
MORPH["車廂寶箱"] = "Railcar Chest"
MORPH["雕座寶箱"] = "Statue-pedestal Chest"
MORPH["沙下寶箱"] = "Sand-buried Chest"
MORPH["工具箱堆"] = "Toolbox Pile"
MORPH["農具棚"] = "Tool Shed"
MORPH["雞舍"] = "Chicken Coop"
MORPH["穀倉筒"] = "Silo"
MORPH["收割機"] = "Harvester"
MORPH["老井"] = "Old Well"
MORPH["獻祭之樹"] = "Tree of Sacrifice"
MORPH["碼頭"] = "Dock"
MORPH["陰森食品間"] = "Eerie Pantry"
MORPH["食品間二樓"] = "Pantry 2F"
MORPH["汽船上層"] = "Steamer Upper Deck"
MORPH["擱淺木筏"] = "Stranded Raft"
MORPH["沉沒神龕"] = "Sunken Shrine"
MORPH["沉沒階"] = "Sunken Stair"
MORPH["深水"] = "Deep Water"
MORPH["淺水"] = "Shallow Water"
MORPH["涉水"] = "Wade"
MORPH["蘆葦"] = "Reed"
MORPH["紅葉海"] = "Red Leaf Sea"
MORPH["紅葉海葉下"] = "Red Leaf Sea (Beneath Leaves)"
MORPH["立石圈"] = "Standing Stone Circle"
MORPH["獵人小屋"] = "Hunter's Cabin"
MORPH["血祭壇"] = "Blood Altar"
MORPH["無名墓"] = "Nameless Grave"
MORPH["拾遺者的隱門"] = "Scavenger's Hidden Door"
MORPH["風蝕洞"] = "Wind-eroded Cave"
MORPH["骨堆"] = "Bone Pile"
MORPH["烏鴉巢"] = "Crow's Nest"
MORPH["法恩的裝置"] = "Fane's Device"
MORPH["東石雕群"] = "East Statue Cluster"
MORPH["西石雕群"] = "West Statue Cluster"
MORPH["石像圈"] = "Stone Statue Circle"
MORPH["塔基"] = "Tower Base"
MORPH["塔頂"] = "Tower Top"
MORPH["裂隙"] = "Rift"
MORPH["天穹裂口"] = "Sky-roof Rift"
MORPH["無盡階"] = "Endless Stair"
MORPH["螺旋梯下段"] = "Spiral Stair Lower"
MORPH["螺旋梯中段"] = "Spiral Stair Mid"
MORPH["無盡階上段梯"] = "Endless Stair Upper Flight"
MORPH["塔門"] = "Tower Door"
MORPH["石廊"] = "Stone Corridor"
MORPH["石門"] = "Stone Door"
MORPH["密道"] = "Secret Passage"
MORPH["暗門"] = "Secret Door"
MORPH["暗渠"] = "Drainage Channel"
MORPH["排水暗渠口"] = "Drainage Outlet"
MORPH["單門"] = "Single Door"
MORPH["地板格柵"] = "Floor Grate"
MORPH["破洞地板"] = "Broken Floor"
MORPH["外牆裂縫"] = "Outer Wall Crack"
MORPH["破口"] = "Breach"
MORPH["牆體"] = "Wall"
MORPH["走廊隔牆"] = "Corridor Partition"
MORPH["翼房間"] = "Wing Room"
MORPH["翼隔牆"] = "Wing Partition"
MORPH["病房隔牆"] = "Ward Partition"
MORPH["病房隔簾"] = "Ward Curtain"
MORPH["病歷架"] = "Records Rack"
MORPH["貨架"] = "Shelf"
MORPH["手術台"] = "Operating Table"
MORPH["病牀"] = "Hospital Bed"
MORPH["觀察窗"] = "Observation Window"
MORPH["觀眾席"] = "Auditorium"
MORPH["觀眾席階梯"] = "Auditorium Stairs"
MORPH["講壇"] = "Pulpit"
MORPH["講壇暗門"] = "Pulpit Secret Door"
MORPH["治療劇場"] = "Treatment Theater"
MORPH["電療室"] = "Electrotherapy Room"
MORPH["藥品櫃"] = "Medicine Cabinet"
MORPH["神父的箱子"] = "Priest's Box"
MORPH["禮拜堂"] = "Chapel"
MORPH["停屍間"] = "Morgue"
MORPH["鐘樓"] = "Bell Tower"
MORPH["接待廳"] = "Reception Hall"
MORPH["坎貝爾神父的禮拜堂"] = "Father Campbell's Chapel"
MORPH["擾動病房·一樓"] = "Disturbed Ward · 1F"
MORPH["擾動病房·二樓"] = "Disturbed Ward · 2F"
MORPH["擾動病房·三樓"] = "Disturbed Ward · 3F"
MORPH["十七號站"] = "Station 17"
MORPH["病歷室"] = "Records Room"
MORPH["單面鏡窗"] = "One-way Mirror Window"
MORPH["天井"] = "Atrium"
MORPH["開口天井底"] = "Opening · Atrium Bottom"
MORPH["石門側室門"] = "Stone Door Side-room Door"
MORPH["主建物"] = "Main Building"
MORPH["建物層"] = "Building Level"
MORPH["建物內"] = "Building Interior"
MORPH["房間"] = "Room"
MORPH["樞紐"] = "Hub"
MORPH["關鍵"] = "Key"
MORPH["死路"] = "Dead End"
MORPH["危險"] = "Hazard"
MORPH["殘影"] = "Afterimage"
MORPH["掩體地標"] = "Cover Landmark"
MORPH["關鍵地標"] = "Key Landmark"
MORPH["主地標"] = "Main Landmark"
MORPH["主場"] = "Main Arena"
MORPH["主區"] = "Main Zone"
MORPH["掩體區"] = "Cover Zone"
MORPH["遮蔽區"] = "Concealment Zone"
MORPH["地標"] = "Landmark"
MORPH["制高點"] = "Vantage Point"
MORPH["特殊"] = "Special"
MORPH["通道"] = "Passage"
MORPH["可選"] = "Optional"
MORPH["入口"] = "Entrance"
MORPH["出口"] = "Exit"
MORPH["開闊區"] = "Open Area"
MORPH["神殿"] = "Temple"
MORPH["孤塔"] = "Lone Tower"
MORPH["無名之心"] = "The Nameless Heart"
MORPH["營火"] = "Campfire"
MORPH["虛空"] = "The Void"
MORPH["領域"] = "Realm"
MORPH["第三幕"] = "Act 3"
MORPH["終局"] = "Endgame"
# generic tail words
MORPH["棧道"] = "Catwalk"
MORPH["棧橋"] = "Pier"
MORPH["徑"] = "Trail"
MORPH["道"] = "Path"
MORPH["區"] = "Zone"
MORPH["室"] = "Room"
MORPH["層"] = "Floor"
MORPH["門"] = "Door"
MORPH["口"] = "Mouth"
MORPH["牆"] = "Wall"
MORPH["梯"] = "Ladder"
MORPH["台"] = "Platform"
MORPH["架"] = "Rack"
MORPH["箱"] = "Chest"
MORPH["洞"] = "Hole"
MORPH["坡"] = "Slope"
MORPH["頂"] = "Top"
MORPH["底"] = "Bottom"
MORPH["緣"] = "Edge"
MORPH["角"] = "Corner"
MORPH["林"] = "Woods"
MORPH["田"] = "Field"

# ---- Remaining exact entries (names/types/notes discovered by diagnosis) ----
# type
TR["收割機（掩體）"] = "Harvester (Cover)"
TR["沙丘（半掩體）"] = "Sand Dune (Half-Cover)"
# names
TR["A 翼·保存室"] = "Wing A · Preservation Room"
TR["A 翼·第一長廊"] = "Wing A · First Long Corridor"
TR["A 翼·第二長廊"] = "Wing A · Second Long Corridor"
TR["A 翼·觀察室"] = "Wing A · Observation Room"
TR["B 翼·保存室"] = "Wing B · Preservation Room"
TR["B 翼·第一長廊"] = "Wing B · First Long Corridor"
TR["B 翼·第二長廊"] = "Wing B · Second Long Corridor"
TR["B 翼·觀察室"] = "Wing B · Observation Room"
TR["S4 戰鬥圖·病歷室封閉遭遇"] = "S4 Battle Map · Sealed Records Room Encounter"
TR["S6 戰鬥圖·治療劇場暴露遭遇"] = "S6 Battle Map · Treatment Theater Exposure Encounter"
TR["S7 戰鬥圖·淨罪神殿內存活"] = "S7 Battle Map · Survival inside Sin-Cleansing Temple"
TR["一層·側室"] = "1F · Side Chamber"
TR["三樓欄杆（瀕死）"] = "3F Railing (Dying)"
TR["上段梯（無餘燼者向上會回到 tw_eyrie）"] = "Upper Ladder (Non-ember-bearers going up return to tw_eyrie)"
TR["下段梯"] = "Lower Ladder"
TR["不可通行，可傳火"] = "Impassable, but Ember can be passed"
TR["中央"] = "Center"
TR["中段梯"] = "Mid Ladder"
TR["主任辦公室"] = "Head Doctor's Office"
TR["二層·錯階"] = "2F · Misaligned Stairs"
TR["二層·鏡廊"] = "2F · Mirror Gallery"
TR["二樓窗"] = "2F Window"
TR["二樓窗跳入水中"] = "2F Window (jump into water)"
TR["你的那一條"] = "Your Path"
TR["保存室門"] = "Preservation Room Door"
TR["倉庫二樓"] = "Warehouse 2F"
TR["側"] = "Side"
TR["側室門（門框太窄）"] = "Side-chamber Door (Frame too narrow)"
TR["僅視線不可通行"] = "Line-of-sight only; impassable"
TR["內圈道"] = "Inner-ring Path"
TR["劇場正門"] = "Theater Main Door"
TR["北廊口"] = "North Gallery Opening"
TR["北廊門"] = "North Gallery Door"
TR["北弧道"] = "North Arc Path"
TR["十七號站的地方"] = "Station 17's Place"
TR["十三號房門"] = "Room 13 Door"
TR["十三號療程室"] = "Therapy Room 13"
TR["吊車基座"] = "Crane Base"
TR["回到地表（時限內）"] = "Return to Surface (within time limit)"
TR["地下梯"] = "Underground Ladder"
TR["地窖漂流點"] = "Hatch Drift Point"
TR["坎貝爾神父的禮拜堂"] = "Father Campbell's Chapel"
TR["壓縮機"] = "Compressor"
TR["外牆裂縫（第三幕後可通行）"] = "Outer Wall Crack (Passable after Act 3)"
TR["外牆邊"] = "Outer Wall Edge"
TR["天井欄杆（跳下至一樓，受傷）"] = "Atrium Railing (Drop to 1F; takes damage)"
TR["屋內"] = "Indoors"
TR["屋前徑"] = "Front-of-house Trail"
TR["屠宰場內部"] = "Slaughterhouse Interior"
TR["屠宰場大門"] = "Slaughterhouse Main Gate"
TR["廢棄病房"] = "Abandoned Ward"
TR["廢棄病房門"] = "Abandoned Ward Door"
TR["排水口"] = "Drainage Outlet"
TR["排水暗渠（完成後開通，永久）"] = "Drainage Channel (Opens after completion; permanent)"
TR["攀根"] = "Climbing Root"
TR["更深處"] = "Deeper"
TR["最後一階"] = "Final Step"
TR["東丘道"] = "East Hill Path"
TR["東廊口"] = "East Gallery Opening"
TR["東雕道"] = "East Statue Path"
TR["校車前後窗"] = "School Bus Front/Rear Window"
TR["根系·中層"] = "Root System · Mid Layer"
TR["根系·深層"] = "Root System · Deep Layer"
TR["根系·近層"] = "Root System · Near Layer"
TR["棚下"] = "Under the Shed"
TR["樹洞"] = "Hollow Tree"
TR["死路·車牆"] = "Dead End · Car Wall"
TR["沙坑"] = "Sand Pit"
TR["油桶巷"] = "Oil-drum Alley"
TR["泵房"] = "Pump Room"
TR["深處"] = "Deep Place"
TR["淺灘"] = "Shoal"
TR["湯普森宅"] = "Thompson House"
TR["湯普森宅二樓"] = "Thompson House 2F"
TR["烏鴉巢環"] = "Crow's Nest Ring"
TR["焦黑玄關"] = "Charred Entrance Hall"
TR["焦黑門廳"] = "Charred Foyer"
TR["獵徑"] = "Hunt Trail"
TR["玄關"] = "Entrance Hall"
TR["病房門"] = "Ward Door"
TR["病歷室前廳"] = "Records Room Antechamber"
TR["病歷室門（唯一出入口）"] = "Records Room Door (Only entrance/exit)"
TR["登船板"] = "Gangplank"
TR["石下"] = "Under the Rock"
TR["石像道"] = "Statue Path"
TR["石徑"] = "Stone Trail"
TR["石環外"] = "Outside Stone Ring"
TR["神殿一層·柱廳"] = "Temple 1F · Pillar Hall"
TR["神父的路"] = "The Priest's Path"
TR["祭道"] = "Ritual Path"
TR["穗間"] = "Between Stalks"
TR["第一段"] = "Segment 1"
TR["第一階（高度不一致）"] = "First Step (Inconsistent height)"
TR["第三段"] = "Segment 3"
TR["第二段"] = "Segment 2"
TR["籠屋群"] = "Cage Hut Cluster"
TR["籠後水路"] = "Cage-back Waterway"
TR["籠道"] = "Cage Path"
TR["縱身"] = "Leap"
TR["聖器室"] = "Sacristy"
TR["腐臭屠宰場"] = "Foul-smelling Slaughterhouse"
TR["舊墳道"] = "Old-grave Path"
TR["舷窗"] = "Porthole"
TR["船艙"] = "Ship Cabin"
TR["葉下（瀕死爬行完全隱蔽）"] = "Beneath Leaves (Dying-crawl fully concealed)"
TR["葉緣"] = "Leaf Edge"
TR["藥品間"] = "Medicine Room"
TR["藥櫃間"] = "Medicine-cabinet Room"
TR["裝置道"] = "Device Path"
TR["西丘道"] = "West Hill Path"
TR["西側逃生梯"] = "West-side Escape Ladder"
TR["西雕道"] = "West Statue Path"
TR["觀察室門"] = "Observation Room Door"
TR["觀察窗（可看，可翻越）"] = "Observation Window (Can see through; climbable)"
TR["觀眾席環廊"] = "Auditorium Ring Corridor"
TR["講壇後"] = "Behind the Pulpit"
TR["谷底"] = "Valley Bottom"
TR["貨卡車斗"] = "Truck Bed"
TR["車堆側面"] = "Car-pile Side"
TR["車廂縫"] = "Railcar Gap"
TR["車牆巷"] = "Car-wall Alley"
TR["辦公室門"] = "Office Door"
TR["通往隱室（S5 解鎖，雙向）"] = "To Hidden Workshop (Unlocks S5; two-way)"
TR["那一條特別細"] = "That Particularly Thin One"
TR["銹縫"] = "Rust Rift"
TR["錯階（回頭走會多一階）"] = "Misaligned Stairs (Backtracking adds a step)"
TR["鏡廊（兩端看起來一樣）"] = "Mirror Gallery (Both ends look identical)"
TR["鐵谷·中段"] = "Canyon · Mid Section"
TR["鐵谷·北段"] = "Canyon · North Section"
TR["鐵谷·南段"] = "Canyon · South Section"
TR["長廊"] = "Long Corridor"
TR["雕座下"] = "Beneath the Pedestal"
TR["風蝕徑"] = "Wind-eroded Trail"
TR["食品間棧道"] = "Pantry Catwalk"
TR["高窗"] = "High Window"
TR["龕側"] = "Niche Side"
# notes (exact, incl. the real grid-cell suffix)
TR["三段深水區，每段敏捷（AGI）或意志（WIL）檢定（DC 困難）；水中浮腫者＝泥手（RC-06）抓住涉水者拖慢移動。座標格位（1 格 = 2 公尺），原點左上。"] = "Three segments of deep water; each requires an Agility (AGI) or Will (WIL) check (DC Difficult). In the water, The Bloated = Mud Hands (RC-06) grabs waders and slows their movement. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["不可通行，可傳火（S8 燎原路線）"] = "Impassable, but Ember can be passed (S8 Conflagration route)"
TR["全圖視覺伏筆；玩家首次看圖即注意到紅線（臍帶），S7 才知是什麼"] = "Full-map visual foreshadowing; players notice the red line (Umbilical) on first sight, only learn what it is in S7"
TR["全戰役唯一封閉空間，近身追逐極致命。座標格位（1 格 = 2 公尺），原點左上。"] = "The only fully enclosed space in the whole campaign; close-quarters chase is extremely lethal. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["唯一單出口戰鬥地圖；護士在玩家進入後才出現在門口，不追進來，只是站著，緩慢敲桌。座標格位（1 格 = 2 公尺），原點左上。"] = "The only single-exit battle map; the Nurse appears at the door only after the player enters, does not chase in, just stands and slowly taps the table. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["塔頂最終追逐，純速度／行動點（AP）；通過天穹裂口（hr_rift）進入無名之心。座標格位（1 格 = 2 公尺），原點左上。"] = "Final chase atop the tower; pure speed / Action Points (AP). Enter The Nameless Heart through the Sky-roof Rift (hr_rift). Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["室內二樓，含窗戶通往煤塔頂；教學：掛鉤（Hook）與救援。座標格位（1 格 = 2 公尺），原點左上。"] = "Interior 2F, with a window to the Coal Tower top; teaches Hooks (Hook) and rescue. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["幽咽護士（NRS）閃現（Blink）可穿越樓層與牆體；全封閉、視線極短。座標格位（1 格 = 2 公尺），原點左上。"] = "The Nurse (NRS) Blink can cross floors and walls; fully enclosed, very short line of sight. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["幽靈（WRT）無恐怖半徑（TR），玩家聽不到心跳；靠聽覺線索判斷方位。座標格位（1 格 = 2 公尺），原點左上。"] = "The Wraith (WRT) has no Terror Radius (TR); players cannot hear a heartbeat, relying on audio cues to judge direction. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["教學追逐，無板子壓力、無造物；GM 必須讓玩家逃掉。座標為格位（1 格 = 2 公尺），原點左上。"] = "Tutorial chase, no pallet pressure, no creations; the GM must let the player escape. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["治療劇場無掩體，極高壓；緘默者（SIL）暴露突襲。座標格位（1 格 = 2 公尺），原點左上。"] = "The Treatment Theater has no cover and is extremely high-pressure; The Silent One (SIL) strikes from exposure. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["泥沼巫婆（HAG）泥符（Mud Glyph）佈局＋幻影瞬移（Phantasm Teleport），可在淺水佈泥像陷阱（雷區）；空間不可信。座標格位（1 格 = 2 公尺），原點左上。"] = "The Hag (HAG) lays Mud Glyphs (Mud Glyph) and Phantasm Teleport (Phantasm Teleport); can place Mud Glyph Traps (minefield) in shallow water; space is untrustworthy. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["灰咽＝病房殘影（RC-05），焦炭狀造物發出病患哀號干擾聽覺辨位。座標格位（1 格 = 2 公尺），原點左上。"] = "Ash Throat = Ward Afterimage (RC-05), a charred creation emitting patients' wails that disrupt audio-based positioning. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["狂徒軍團（LGN）狂暴（Frenzy）連續突進，擊中施加深傷（Deep Wound），非移動時持續流失——「停下來就是死」。座標格位（1 格 = 2 公尺），原點左上。"] = "Legion (LGN) Frenzy drives continuous charges; hits inflict Deep Wound (Deep Wound); when not moving, HP steadily drains — 'stop and you die'. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["獵斧女（HTR）或緘默者（SIL）依 S6 選擇；存活輪數見 S7 人數表"] = "Huntress (HTR) or The Silent One (SIL), chosen per S6; survival rounds per the S7 player-count table"
TR["獵斧女（HTR）手斧（Hand Axe）遠程投擲，距離帶（Distance Band）3 以內目標皆可攻擊，巨樹是唯一防護；開闊林地無安全距離。座標格位（1 格 = 2 公尺），原點左上。"] = "Huntress (HTR) throws Hand Axes (Hand Axe) at range; any target within Distance Band 3 can be hit; the Giant Tree is the only cover; open woods have no safe distance. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["穗行者＝稻草殘影（RC-04），藏在玉米田中模仿撥開玉米的聲音誤導玩家（實傷✓）。座標格位（1 格 = 2 公尺），原點左上。"] = "The Stalk-row Walker = Straw Afterimage (RC-04), hides in the cornfield mimicking the sound of parting corn to mislead players (real damage ✓). Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["緘默者（SIL）無恐怖半徑（TR）（無心跳，最大恐怖來源）；GM 完全不敲桌。座標格位（1 格 = 2 公尺），原點左上。"] = "The Silent One (SIL) has no Terror Radius (TR) (no heartbeat, the greatest source of dread); the GM never taps the table. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["若營火餘燼（Campfire Ember）< 門檻，須在神殿內存活指定輪數後帶餘燼離開（傳奇難度）。座標格位（1 格 = 2 公尺），原點左上。"] = "If the Campfire Ember (Campfire Ember) < threshold, you must survive a set number of rounds inside the temple, then leave with the ember (Legendary difficulty). Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["觸發後通道封閉，敏捷（AGI）閃避。座標格位（1 格 = 2 公尺），原點左上。"] = "After triggering, the passage seals; Agility (AGI) to dodge. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["護士在門口（o1），不主動追入，緩慢敲桌"] = "The Nurse is at the door (o1), does not actively chase in, slowly taps the table"
TR["鏡像交換發生時，A/B 兩翼對稱節點 label 互換、id 不變，地圖記憶失效一次。座標格位（1 格 = 2 公尺），原點左上；左右完全對稱。"] = "When Mirror Swap occurs, the symmetric nodes of wings A/B swap their labels, id unchanged; map memory fails once. Coordinates in grid cells (1 cell = 2 m); origin top-left; fully left-right symmetric."
TR["鏡像對稱設計——wing_a 與 wing_b 節點結構完全相同；「鏡像交換」發生時，兩翼 label 互換、id 不變。"] = "Mirror-symmetric design — wing_a and wing_b nodes have identical structure; when 'Mirror Swap' occurs, the two wings swap their labels, id unchanged."
TR["開闊地是鏈鋸屠夫（HBY）主場，全戰役到目前最痛的一場；只有 1 面板子（Pallet），靠玉米田遮蔽玩心理戰。座標格位（1 格 = 2 公尺），原點左上。"] = "Open ground is the Hillbilly's (HBY) home turf, the most painful fight so far this campaign; only 1 flat pallet (Pallet), using cornfield concealment for mind games. Coordinates in grid cells (1 cell = 2 m); origin top-left."
TR["霧窖節點與地表座標重疊是刻意的——霧窖在空間上就在農場底下，是同一位置的另一層。"] = "The Fog Cellar node deliberately overlaps surface coordinates — spatially the Fog Cellar sits beneath the farm, another layer of the same location."
TR["玩家進入 t3 範圍或受到攻擊時，t3 格位變為不可通行（封閉通道）"] = "When the player enters t3's area or is attacked, t3's cell becomes impassable (sealed passage)"

# Build sorted TR keys by length (desc) for exact replacement
TR_KEYS = sorted(TR.keys(), key=len, reverse=True)
MORPH_KEYS = sorted(MORPH.keys(), key=len, reverse=True)

def morph_replace(t):
    changed = True
    while changed:
        changed = False
        # exact dictionary hits first (so sub-parts like 麥克米蘭莊園 translate)
        for k in TR_KEYS:
            if k in t:
                t = t.replace(k, TR[k])
                changed = True
        for m in MORPH_KEYS:
            if m in t:
                t = t.replace(m, MORPH[m])
                changed = True
    # collapse multiple spaces, trim
    t = re.sub(r'\s+', ' ', t).strip()
    return t

def translate_value(v):
    v = v.strip()
    if v in TR:
        return TR[v]
    # trailing parenthetical code, e.g. 外圍林地（outer_woods）
    mm = re.match(r'^(.*)（([^）]+)）$', v)
    if mm:
        body, code = mm.group(1), mm.group(2)
        tb = TR.get(body, morph_replace(body))
        return tb + " (" + code + ")"
    # fallback: morpheme decomposition
    return morph_replace(v)

def convert_parens(s):
    return s.replace('（', '(').replace('）', ')')

# ---------------------------------------------------------------------------
# YAML translation: translate each field value as a unit.
# ---------------------------------------------------------------------------
# Flow-style keys appear inside { ... } (nodes/edges/spawn/regions). Paren-aware
# so a value like 麥克米蘭莊園（MacMillan Estate, R1） is not split on the comma.
FLOW_KEYS = ['name','type','region','channel','note','condition','realm','scene','說明','中文名','底色']
# Block-style keys appear at line start (meta / world-map nodes / notes / triggers).
BLOCK_KEYS = ['name','type','region','channel','note','condition','說明','中文名','底色','realm','scene','regions','collapse_trigger']

def _flow_val_replace(line):
    def fl(m):
        key, val = m.group(1), m.group(2)
        tv = convert_parens(translate_value(val))
        # In YAML flow context a value containing a flow-special character
        # (notably a comma introduced by translation) must be double-quoted.
        if re.search(r'[,{}\[\]:#]', tv):
            tv = '"' + tv.replace('"', '\\"') + '"'
        return key + ": " + tv
    return re.sub(r'(%s):[ ]*((?:[^,}]|（[^）]*）)*)' % '|'.join(FLOW_KEYS), fl, line)

def translate_yaml(text):
    out = []
    for ln in text.replace('\r', '').split('\n'):
        s = ln.strip()
        if s.startswith('#'):
            body = s[1:]
            tb = TR.get('#' + body)
            if tb is None:
                tb = convert_parens(translate_value(body))
            else:
                tb = convert_parens(tb)
                if tb.startswith('#'):
                    tb = tb[1:]
            out.append('#' + tb)
            continue
        if '{' in ln:
            out.append(_flow_val_replace(ln))
            continue
        m = re.match(r'^(\s*)(%s):[ ]*(.*)$' % '|'.join(BLOCK_KEYS), ln)
        if m:
            lead, key, val = m.group(1), m.group(2), m.group(3)
            tv = convert_parens(translate_value(val))
            # A YAML block plain scalar may not contain ': ' (colon + space);
            # quote it if needed to keep the file valid.
            if re.search(r': ', tv) or '"' in tv:
                tv = '"' + tv.replace('"', '\\"') + '"'
            out.append(lead + key + ": " + tv)
        else:
            out.append(ln)
    return '\n'.join(out)

# ---------------------------------------------------------------------------
# SVG translation: translate each <text> content as a unit.
# ---------------------------------------------------------------------------
def translate_svg(text):
    def tx(m):
        tag_open = m.group(1)
        inner = m.group(2)
        # inner may contain nested tags (e.g. <tspan>); translate only text nodes
        def txt_repl(tm):
            content = tm.group(0)
            if re.search(r'[\u4e00-\u9fff]', content):
                return convert_parens(translate_value(content))
            return content
        # replace text between tags
        new_inner = re.sub(r'>([^<]+)<', lambda x: '>' + (convert_parens(translate_value(x.group(1))) if re.search(r'[\u4e00-\u9fff]', x.group(1)) else x.group(1)) + '<', inner)
        # also handle case where inner has no child tags: <text ...>CONTENT</text>
        if not re.search(r'<[^>]+>', inner):
            new_inner = convert_parens(translate_value(inner)) if re.search(r'[\u4e00-\u9fff]', inner) else inner
        return '<text' + tag_open + '>' + new_inner + '</text>'
    text = re.sub(r'<text([^>]*)>(.*?)</text>', tx, text, flags=re.S)
    return text

# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------
def main():
    yaml_files = sorted(glob.glob(os.path.join(SRC, "*.yaml")))
    svg_files = sorted(glob.glob(os.path.join(SRC, "*.svg")))
    for f in yaml_files + svg_files:
        base = os.path.basename(f)
        with open(f, encoding='utf-8') as fh:
            text = fh.read()
        if f.endswith('.yaml'):
            out = translate_yaml(text)
        else:
            out = translate_svg(text)
        dst = os.path.join(DST, base)
        with open(dst, 'w', encoding='utf-8') as fh:
            fh.write(out)
        print("wrote", dst)

if __name__ == '__main__':
    main()
